### ISSUE TITLE
WDA Issue - Possibly timing related

### ISSUE THREAD

**Issue by himanshunamdeo** [nanoscopic/ios_remote_provider#11]
Hi @nanoscopic,

When i try to run ios remote provider, it fails with the following error log: 

Location from redirect of controlfloor login:'https://localhost:8080/provider/'
Logged in to control floor
self signed option
link for dialer = wss://localhost:8080/provider/ws
INFO[0000] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
Creating IIFDev with udid=<UDID>
udid: <UDID>
Running bin/iosif [mg -json -id <UDID> main-screen-width main-screen-height main-screen-scale]
json:{
"main-screen-width":1125
,
"main-screen-height":2436
,
"main-screen-scale":3

}

Notified control floor of 'device existence'; uuid=***002E
udid for info: <UDID>
json:{
DeviceName:"iPhone"
,
EthernetAddress:"50:7a:c5:bf:c7:c9"
,
ModelNumber:"MT9E2"
,
HardwareModel:"D321AP"
,
ProductType:"iPhone11,2"
,
ProductVersion:"13.7"
,
UniqueDeviceID:"<UDID>"
,
InternationalMobileEquipmentIdentity:"353166101068569"
,
}

mapped result:map[DeviceName:iPhone EthernetAddress:50:7a:c5:bf:c7:c9 HardwareModel:D321AP InternationalMobileEquipmentIdentity:353166101068569 ModelNumber:MT9E2 ProductType:iPhone11,2 ProductVersion:13.7 UniqueDeviceID:<UDID>]
INFO[0000] Device Info                                   info="map[DeviceName:iPhone EthernetAddress:50:7a:c5:bf:c7:c9 HardwareModel:D321AP InternationalMobileEquipmentIdentity:353166101068569 ModelNumber:MT9E2 ProductType:iPhone11,2 ProductVersion:13.7 UniqueDeviceID:<UDID>]" type=devInfo uuid="***002E"
Notified control floor of 'device info'; uuid=***002E
Tunnel from 8102 to 8100
Starting bin/iosif with [tunnel -id <UDID> 8102:8100]
Tunnel from 8102 to 8100
bound to port 8102
Found file repos/WebDriverAgent/build/Build/Products
Found file repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
testrun = repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
port = 8105
id = <UDID>
INFO[0002] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
INFO[0002] Process start - backupVideo                   binary=bin/iosif id=<UDID> port=8105 proc=backupVideo type=proc_start
INFO[0002] listening on tcp://127.0.0.1:8105             proc=backupVideo
listening on tcp://127.0.0.1:8105
Got connection to port
panic: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:49458->127.0.0.1:8102: read: connection reset by peer

goroutine 36 [running]:
main.(*WDA).create_session(0xc000214930, 0x0, 0x0, 0xc00032a9c0, 0xc00036a200)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/wda.go:202 +0x3a5
main.(*WDA).ensureSession(0xc000214930)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/wda.go:161 +0x3a
main.(*Device).enableVideo(0xc0000e0640)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/device.go:236 +0x74
main.(*Device).startProcs(0xc0000e0640)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/device.go:205 +0xd4
main.(*DeviceTracker).onDeviceConnect1(0xc0001e8550, 0x4474f20, 0xc00002c2c0, 0xc00023e0d0)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/device_tracker.go:100 +0x398
main.NewDeviceTracker.func1(0x4474f20, 0xc00002c2c0, 0xc000020c20, 0x19)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/device_tracker.go:42 +0x3e
main.(*IIFBridge).OnConnect(0xc0001e4180, 0xc000020c20, 0x19, 0xc000022940, 0x6, 0xc0001d07e0)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/bridge_iif.go:86 +0xc8
main.(*IIFBridge).startDetect.func2(0xc000025000, 0x3f, 0xc0001d07e0)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/bridge_iif.go:62 +0x29a
main.proc_generic.func1(0xc0001d07e0, 0xc0001ae780, 0xc0001f0180, 0xc0001ae690, 0xc0001ae750, 0xc0001c2180, 0xc0001b8868, 0x0, 0x0)
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/proc_generic.go:189 +0xd94
created by main.proc_generic
	/Users/MeTaLlOiD/Desktop/ControlFoor/24th March/ios_remote_provider/proc_generic.go:105 +0x626

**Comment by ormoran** [comment]
Hi, this error is being shown directly in the terminal? Just asking - my provider instance exits immediately without any error :(

**Comment by nanoscopic** [comment]
I've seen another user with this same issue. It appears to be a timing issue. WDA is trying to be used by the code before WDA is ready. There is a sleep in the code currently to give WDA time to startup, but I believe it is only 6 seconds and not long enough for all users/device types.

I will alter the code to wait for WDA to be ready instead of using the hacky sleep.

**Comment by himanshunamdeo** [comment]
> Hi, this error is being shown directly in the terminal? Just asking - my provider instance exits immediately without any error :(

Yes @ormoran , this is the terminal log.

**Comment by asmiou** [comment]
Hi everyone, I also have the same error. Someone would have a solution please.
@nanoscopic

**Comment by plaguez137** [comment]
Just adding a comment, I'm having this issue as well.  Thanks for any fix.

**Comment by nanoscopic** [comment]
I have altered iosif to output 'Ready' when port forwarding is done, and am in process of changing the provider to use this to avoid the timing issue I described. Update to this soon as a result.

Please also test to see if `./main wda` works or not to test wda functionality alone.

**Comment by kristeedev** [comment]
Attached multiple devices to a host and ran main run, breaks at create WDA session point.

```INFO[0001] listening on tcp://127.0.0.1:8105             proc=backupVideo
listening on tcp://127.0.0.1:8105
panic: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:64489->127.0.0.1:8102: read: connection reset by pee
r

goroutine 35 [running]:
main.(*WDA).create_session(0xc0001caf50, 0x0, 0x0, 0xc0003542a0, 0xc0001cc9a0)```

Tried to run ./main wda to see but get the following out. It seems like it is stuck at the first device:
``` ./main wda
WARN[0000] Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
WARN[0000] Leftover iosif - Sending SIGTERM              pid=27175 proc=iosif type=proc_cleanup
WARN[0000] Leftover iosif - Sending SIGTERM              pid=27180 proc=iosif type=proc_cleanup
WARN[0000] Leftover iosif - Sending SIGTERM              pid=27181 proc=iosif type=proc_cleanup
WARN[0001] Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
Dev id: XXXXXXX-XXXXXXXXXXXXXXX
Creating IIFDev with udid=XXXXXXX-XXXXXXXXXXXXXXX 
Starting bin/iosif with [tunnel -id XXXXXXX-XXXXXXXXXXXXXXX 8100:8100]
INFO[0002] Process start - tunnel_8100->8100             binary=bin/iosif proc="tunnel_8100->8100" type=proc_start
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ```

**Comment by chewbacca70** [comment]
I also faced the Problem of missing calculated_json when make wda. It seems with the latest changes the file is simply missing.
I fixed it with just creating the file via:
touch repos/versionMarkers/calculated_json

maybe also helps you 🤔

**Comment by nanoscopic** [comment]
@chewbacca70 

The file in question was added in the last commit 7 days ago, so one should not have to create one. https://github.com/nanoscopic/ios_remote_provider/commit/3e6cf4a019363bdc7c08517e148cb8252567fcc5

Also, I updated the code so it should work properly even without a calculated.json file being created.

If someone encounters an issue with this on the latest commit please let me know, as such a manual `touch` step should not be required.

@kristeedev 

`./main wda` will only start WDA for a single device as a diagnostic method. It would though be useful for there to be a similar command to do it for all devices, or for a specific one. Will add something for that.

I think there is currently an issue auto-starting vidtest via wda. I don't think the code is properly waiting for wda to be ready to try to run wda commands, and hence wda session creation is breaking for some users but not others in a timing dependent way.

For now the way to avoid that is by starting vidtest before starting provider; in which case provider will not crash at the place in question.

**Comment by nanoscopic** [comment]
@chewbacca70 

Great to hear! Thanks for responding and noting it works for you now. There were a few changes to address timing related issues with the most recent changes, and I will continue to make more changes to address it completely.

Additionally, I am working on improving the way video works to be able to more flexibly handle the situation where it doesn't start up, is not started, or goes down. Once those changes are complete the startup issues many have had should be completely resolved.

The main reasons for the various problems users have been encountering:
1. The vidtest app for streaming video is currently required. If a fallback to another mechanism exists that will prevent vidtest issues from completely breaking startup.
1. Starting up the vidtest app to stream video requires using WDA.
1. Using WDA immediately after it is started is finicky, so there must be detection of failure and re-attempt on fail. Currently no re-attempt is done and it simply breaks. I've been debating adding a queue for WDA requests, as this is also an issue generally with WDA; when WDA has problems it tends to cause cascading issues if whatever is calling WDA is not very resilient.
1. Essentially whenever using WDA one must assume that WDA may simply explode instead of actually working. This has not been done in the code currently and will need to be done to prevent WDA issues from crashing the provider.

**Comment by nanoscopic** [comment]
This is related to the video app being started automatically. The way that has been done has been changed a lot and the errors described should not occur any longer.
