### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by dunkbing** [nanoscopic/ios_remote_provider#13]
@nanoscopic Hi. I'm having an issue while running "make"
`16:34:25:~/Documents/nanoscopic/ios_remote_provider % make`
`make -C repos/ujsonin gojq && touch bin/gojq`
`go build -o gojq gojq.go`
`go: github.com/nanoscopic/uclop@v1.1.0: missing go.sum entry; to add it:`
        `go mod download github.com/nanoscopic/uclop`
`make[1]: *** [gojq] Error 1`
`make: *** No rule to make target 'config.mk', needed by 'main'.  Stop.`

**Comment by plaguez137** [comment]
Greetings.  I just encountered the same issue.  Attempted the `go mod download github.com/nanoscopic/uclop` line, to no avail.

**Comment by plaguez137** [comment]
@dunkbing , I don't know what I've done exactly, but I successfully ran `make`.  Maybe it will work for you.

I learned that I can inspect the output of the `download` command by running `go mod download -json github.com/nanoscopic/uclop`.  I did this from the `uclop` directory.  My output showed all was well:

`me@mymachine ujsonin % go mod download -json github.com/nanoscopic/uclop
{
	"Path": "github.com/nanoscopic/uclop",
	"Version": "v1.1.0",
	"Info": "/Users/me/go/pkg/mod/cache/download/github.com/nanoscopic/uclop/@v/v1.1.0.info",
	"GoMod": "/Users/me/go/pkg/mod/cache/download/github.com/nanoscopic/uclop/@v/v1.1.0.mod",
	"Zip": "/Users/me/go/pkg/mod/cache/download/github.com/nanoscopic/uclop/@v/v1.1.0.zip",
	"Dir": "/Users/me/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0",
	"Sum": "h1:fV2sQtzI1BkXuyqRUqPdark//m/XkyNJeGmikUt3844=",
	"GoModSum": "h1:vt+mTEEFoR1bgrwIZEHut/OM4bjfJOQsmNSIHnXyU9c="
}`

So, I didn't believe I had changed anything. However, some time later I ran `make`, also from the 'uclop' directory, and it ran successfully.  I then backed up to the `ios_remote_provider` directory, ran `make` successfully from there as well.
