### ISSUE TITLE
disable logs

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#14]
Hi,

I just finished setting up the latest commit, and I see that its generating a lot of logs as follows.

```
Tunnel from 8103 to 8352
bound to port 8103
Tunnel from 8104 to 8351
bound to port 8104
Could not parse:[[nnoxs-iPhon,"","istnoted[74] <Notice",`register name: ACDAccountStoreDidChangeNotification object: kCFNotificationAnyObject token: 100000000 pid: 997`]]
Could not parse:[[nnoxs-iPhon,"","ccountsd(AccountsDaemon)[122] <Notice",`"<private> (<private>) received"`]]
Could not parse:[[nnoxs-iPhon,"","ircleJoinRequested(CoreCDP)[997] <Notice",`"Checking iCDP status for DSID <private> (checkWithServer=0)"`]]
Could not parse:[[nnoxs-iPhon,"","rustd[143] <Notice",`cert[0]: MissingIntermediate =(leaf)[force]> 0`]]
Could not parse:[[nnoxs-iPhon,"","rustd[143] <Notice",`cert[0]: NonEmptySubject =(path)[]> 0`]]
Could not parse:[[nnoxs-iPhon,"","eplayd[270] <Error",` [ERROR] -[RPSession dispatchLimitReached:]:1490 reached max dispatch count, dropping sample of type 2`]]
Could not parse:[[nnoxs-iPhon,"","dpd(ProtectedCloudStorage)[137] <Notice",`KeychainGetStatus(PCSiCloudServiceMarkerName): keychain: 0`]]
Could not parse:[[nnoxs-iPhon,"","dpd(ProtectedCloudStorage)[137] <Notice",`KeychainGetStatus(PCSiCloudServiceMarkerName): status: on`]]
Could not parse:[[nnoxs-iPhon,"","ircleJoinRequested(CoreCDP)[997] <Notice",`"iCDP status for DSID <private> is ENABLED"`]]
Could not parse:[[nnoxs-iPhon,"","ircleJoinRequested[997] <Notice",`iCDP: PSKeychainSyncIsUsingICDP returning TRUE`]]
Could not parse:[[nnoxs-iPhon,"","ircleJoinRequested(CoreCDP)[997] <Error",`"Daemon connection invalidated!"`]]
Could not parse:[[nnoxs-iPhon,"","ircleJoinRequested[997] <Notice",`account is icdp: 1`]]
Could not parse:[[nnoxs-iPhon,"","ockdownd[70] <Notice",`handle_get_value: <private>`]]
Could not parse:[[nnoxs-iPhon,"","ecurityd[116] <Notice",`Starting as:member v:{(AccessoryPairing, AppleTV, BackupBagV0, ContinuityUnlock, CreditCards, HomeKit, NanoRegistry, OtherSyncable, PCS-Backup, PCS-CloudKit, PCS-Escrow, PCS-FDE, PCS-Feldspar, PCS-Maildrop, PCS-MasterKey, PCS-Notes, PCS-Photos, PCS-Sharing, PCS-iCloudDrive, PCS-iMessage, Passwords, WatchMigration, WiFi, iCloudIdentity)}`]]
```

Also, the WDA stops and starts for some reason, and below is detailed,
xcode - 12.4

Thanks

**Comment by AdamDuongIt** [comment]
I got same issue here, running Xcode 12.4

`11:30:30:~/Documents/workspace/ios_remote_provider % ./main run
WARN[0000] Leftover iosif - Sending SIGTERM              pid=3920 proc=iosif type=proc_cleanup
WARN[0000] Leftover iosif - Sending SIGTERM              pid=3923 proc=iosif type=proc_cleanup
INFO[0001] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
Location from redirect of controlfloor login:'http://localhost:8080/provider/'
Logged in to control floor
link for dialer = ws://localhost:8080/provider/ws
Creating IIFDev with udid=00008020-000445CE3A84402E
udid: 00008020-000445CE3A84402E
Running bin/iosif [mg -json -id 00008020-000445CE3A84402E AvailableDisplayZoomSizes main-screen-width main-screen-height]
json:{
"AvailableDisplayZoomSizes":{
  default:[
    2
    414
    2
    896
  ]
  zoomed:[
    2
    375
    2
    812
  ]
}
,
"main-screen-width":828
,
"main-screen-height":1792

}

Notified control floor of 'device existence'; uuid=***402E
udid for info: 00008020-000445CE3A84402E
json:{
DeviceName:"iPhone"
,
EthernetAddress:"a8:91:3d:bf:47:c8"
,
ModelNumber:"MH6M3"
,
HardwareModel:"N841AP"
,
PhoneNumber:"+84 98 8015933"
,
ProductType:"iPhone11,8"
,
ProductVersion:"14.4.2"
,
UniqueDeviceID:"00008020-000445CE3A84402E"
,
InternationalMobileEquipmentIdentity:"352886117345567"
,
}

mapped result:map[DeviceName:iPhone EthernetAddress:a8:91:3d:bf:47:c8 HardwareModel:N841AP InternationalMobileEquipmentIdentity:352886117345567 ModelNumber:MH6M3 PhoneNumber:+84 98 8015933 ProductType:iPhone11,8 ProductVersion:14.4.2 UniqueDeviceID:00008020-000445CE3A84402E]
INFO[0001] Device Info                                   info="map[DeviceName:iPhone EthernetAddress:a8:91:3d:bf:47:c8 HardwareModel:N841AP InternationalMobileEquipmentIdentity:352886117345567 ModelNumber:MH6M3 PhoneNumber:+84 98 8015933 ProductType:iPhone11,8 ProductVersion:14.4.2 UniqueDeviceID:00008020-000445CE3A84402E]" type=devInfo uuid="***402E"
Notified control floor of 'device info'; uuid=***402E
Tunnel from 8102 to 8100
Starting bin/iosif with [tunnel -id 00008020-000445CE3A84402E 8102:8100]
Tunnel from 8102 to 8100
bound to port 8102
port = 8105
id = 00008020-000445CE3A84402E
INFO[0003] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
INFO[0003] Process start - backupVideo                   binary=bin/iosif id=00008020-000445CE3A84402E port=8105 proc=backupVideo type=proc_start
WARN[0003] Process end - wda                             proc=wda type=proc_end
INFO[0003] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
Notified control floor of 'wda stop'; uuid=***402E
INFO[0003] listening on tcp://127.0.0.1:8105             proc=backupVideo
listening on tcp://127.0.0.1:8105
WARN[0004] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***402E
id = 00008020-000445CE3A84402E
Tunnel from 8103 to 8352
Tunnel from 8104 to 8351
Starting bin/iosif with [tunnel -id 00008020-000445CE3A84402E 8103:8352 8104:8351]
INFO[0004] Process start - syslogMonitor                 binary=bin/iosif id=00008020-000445CE3A84402E proc=syslogMonitor type=proc_start
Tunnel from 8103 to 8352
bound to port 8103
Tunnel from 8104 to 8351
bound to port 8104
Could not parse:[[on,"","idtest2(ReplayKit)[4311] <Notice",` [INFO] -[RPBroadcastSampleHandler _processPayloadWithAudioSample:type:]:178 Broadcast extension received audio payload from replayd`]]
Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPSystemBroadcastSession notifyExtensionOfAudioSampleBuffer:withType:]_block_invoke_2:568 Sending 2 audio payload to broadcast extension...`]]
Could not parse:[[on,"","ircleJoinRequested(CoreCDP)[4314] <Notice",`"Checking iCDP status for DSID <private> (checkWithServer=0)"`]]
Could not parse:[[on,"","rustd[139] <Notice",`cert[0]: MissingIntermediate =(leaf)[force]> 0`]]
Could not parse:[[on,"","rustd[139] <Notice",`cert[0]: NonEmptySubject =(path)[]> 0`]]
Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPScreenCaptureManagerIOS screenCaptureController:didReceiveSampleBuffer:transformFlags:]:104 screen sampled at window size width:828 heigth:1792 transformFlags 0`]]
Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPSystemBroadcastSession processSampleBuffer:transformFlags:]:529 processing sample buffer for streaming`]]
Could not parse:[[on,"","idtest2(ReplayKit)[4311] <Notice",` [INFO] -[RPBroadcastSampleHandler _processPayloadWithVideoSample:]:148 Broadcast extension received video payload from replayd`]]
Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPSystemBroadcastSession notifyExtensionOfVideoSampleBuffer:withType:sampleOrientation:]_block_invoke_2:617 Sending video payload to broadcast extension...`]]
Could not parse:[[on,"","ockdownd[3321] <Notice",`handle_get_value: <private>`]]
Could not parse:[[on,"","dpd(ProtectedCloudStorage)[1333] <Notice",`KeychainGetStatus(PCSiCloudServiceMarkerName): keychain: 0`]]
Could not parse:[[on,"","dpd(ProtectedCloudStorage)[1333] <Notice",`KeychainGetStatus(PCSiCloudServiceMarkerName): status: on`]]
Could not parse:[[on,"","ircleJoinRequested(CoreCDP)[4314] <Notice",`"iCDP status for DSID <private> is ENABLED"`]]
Could not parse:[[on,"","ircleJoinRequested(CoreCDP)[4314] <Error",`"Daemon connection invalidated!"`]]
Could not parse:[[on,"","ircleJoinRequested[4314] <Notice",`iCDP: PSKeychainSyncIsUsingICDP returning TRUE`]]
Could not parse:[[on,"","ircleJoinRequested[4314] <Notice",`account is icdp: 1`]]
Could not parse:[[on,"","ecurityd[1331] <Notice",`Starting as:member v:{(AccessoryPairing, AppleTV, BackupBagV0, ContinuityUnlock, HomeKit, NanoRegistry, PCS-Backup, PCS-CloudKit, PCS-Escrow, PCS-FDE, PCS-Feldspar, PCS-Maildrop, PCS-MasterKey, PCS-Notes, PCS-Photos, PCS-Sharing, PCS-iCloudDrive, PCS-iMessage, WatchMigration, iCloudIdentity)}`]]
Could not parse:[[on,"","idtest2(ReplayKit)[4311] <Notice",` [INFO] -[RPBroadcastSampleHandler _processPayloadWithAudioSample:type:]:178 Broadcast extension received audio payload from replayd`]]
Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPSystemBroadcastSession notifyExtensionOfAudioSampleBuffer:withType:]_block_invoke_2:568 Sending 2 audio payload to broadcast extension...`]]
Could not parse:[[on,"","ecurityd[1331] <Notice",`Finished as:member v:{(AccessoryPairing, AppleTV, BackupBagV0, ContinuityUnlock, HomeKit, NanoRegistry, PCS-Backup, PCS-CloudKit, PCS-Escrow, PCS-FDE, PCS-Feldspar, PCS-Maildrop, PCS-MasterKey, PCS-Notes, PCS-Photos, PCS-Sharing, PCS-iCloudDrive, PCS-iMessage, WatchMigration, iCloudIdentity)}`]]
Could not parse:[[on,"","ircleJoinRequested(Security)[4314] <Notice",`Retrieved non-cached circle value 0`]]
Could not parse:[[on,"","ircleJoinRequested[4314] <Notice",`follow up should be resolved`]]`

**Comment by nanoscopic** [comment]
This was a bug due to the log parsing being dependent on having a 1 character phone name. I have now corrected this bug and it should work properly.

If you still have an issue, please provide a fragment of the output of the log command with the '-raw' option so that I can understand how the parsing is failing.
