### ISSUE TITLE
make wda issue

### ISSUE THREAD

**Issue by dunkbing** [nanoscopic/ios_remote_provider#15]
try to run make wda with updated config.json which include my apple developer account, but got this error
`error: Failed to register bundle identifier: The app identifier "com.appium.WebDriverAgentRunner.xctrunner" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')`
`error: No profiles for 'com.appium.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.appium.WebDriverAgentRunner.xctrunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')`
`error: Failed to register bundle identifier: The app identifier "com.facebook.IntegrationApp" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again. (in target 'IntegrationApp' from project 'WebDriverAgent')`
`error: No profiles for 'com.facebook.IntegrationApp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.IntegrationApp'. (in target 'IntegrationApp' from project 'WebDriverAgent')`

`2021-05-04 15:31:24.748 xcodebuild[8594:129522] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/gameloft/Documents/nanoscopic/ios_remote_provider/repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fa059ffe1f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by kristeedev** [comment]
Hello @dunkbing , please edit config.json. Add devTeamOu and bundlePrefix (you need a paid apple developer account for this). To get these details - make sure Xcode is logged in for that particular user in the MAC. Once it is logged in successfully, please unlock keychain for your MAC in the terminal to make sure that the certificates are visible.
`security unlock-keychain login.keychain `
Once this is done, run `./util/signers.pl` to get the details. Try building wda by running `./main wda`. It should build successfully after these steps.

**Comment by nanoscopic** [comment]
@dunkbing If you are not using a paid developer account, then xcode will refuse to reuse an existing bundle identifier. You can change the bundle id prefix as @kristeedev said in order to work around this.
