### ISSUE TITLE
Some devices lack AvailableZoomSizes mobile gestalt info

### ISSUE THREAD

**Issue by kristeedev** [nanoscopic/ios_remote_provider#16]
Hello @nanoscopic sir,

The new check in is failing at this point when I run provider `./main run`
```panic: runtime error: index out of range [1] with length 0goroutine 9 [running]:
github.com/nanoscopic/ujsonin/v2/mod.(*JArr).GetAt(0xc00009c630, 0x1, 0x7, 0x4428ec8)
        github.com/nanoscopic/ujsonin/v2@v2.0.4/mod/ujsonin.go:77 +0x4b
main.(*DeviceTracker).onDeviceConnect1(0xc000107c70, 0x4429368, 0xc00005cb00, 0xc00021e8f0)
        ios_remote_provider/device_tracker.go:111 +0x41e
main.NewDeviceTracker.func1(0x4429368, 0xc00005cb00, 0xc0000153e0, 0x19)
        ios_remote_provider/device_tracker.go:45 +0x3e
main.(*IIFBridge).OnConnect(0xc00005c7c0, 0xc0000153e0, 0x19, 0xc00027e010, 0x6, 0xc000107ce0)
        ios_remote_provider/bridge_iif.go:86 +0xc8
main.(*IIFBridge).startDetect.func2(0xc000021e80, 0x3f, 0xc000107ce0)
        ios_remote_provider/bridge_iif.go:62 +0x29a
main.proc_generic.func1(0xc000107ce0, 0xc0002146c0, 0xc000154200, 0xc000214600, 0xc000214690, 0xc00006a120, 0xc000016b88, 0x0, 0x0)
        ios_remote_provider/proc_generic.go:190 +0xe4f
created by main.proc_generic
        ios_remote_provider/proc_generic.go:105 +0x626```

**Comment by nanoscopic** [comment]
I've never seen it break in this way. You'll need to state the specific commit this error occurs at in order for me to determine which line of code it is crashing on and guess the cause.

What commit does this occur on?

**Comment by nanoscopic** [comment]
This looks to be a result of AvailableZoomSizes mobile gestalt data not being available on all device types.
See https://github.com/nanoscopic/ios_remote_provider/blob/main/device_tracker.go#L109

There is a workaround in place for this. You can add a 'devices' block of configuration manually specifying the width and height of your device. See https://github.com/nanoscopic/ios_remote_provider/blob/main/config.go#L89 for now.

Need to write documentation on this and add it to the readme so it is easy to understand how to resolve this.

Also need to create some automated method of handling this to prevent having to add such a manual configuration block to config.json.

**Comment by nanoscopic** [comment]
The documentation for this has been added to the readme at the bottom.

For now that will suffice.
