### ISSUE TITLE
Ujsonin build issue. Golang module finickyness.

### ISSUE THREAD

**Issue by ababushkin-bscmsc** [nanoscopic/ios_remote_provider#17]
make -C repos/ujsonin gojq && touch bin/gojq
go build -o gojq gojq.go
go: github.com/nanoscopic/uclop@v1.1.0: missing go.sum entry; to add it:
go mod download github.com/nanoscopic/uclop
make[1]: *** [gojq] Error 1
make: *** No rule to make target 'config.mk', needed by 'main'. Stop.

I do everything according to the instructions, but I can't do it
Installed last version go.lang
Mac OS Big Sur 11.2.3
Node JS 8.10

Help me please @nanoscopic

**Comment by nanoscopic** [comment]
Pretty sure this is just wanting go.mod to be updated. What is odd to me is that this does not cause the above error on all systems. It is relatively easy to work around by following the instruction given though. ( go mod download... )

**Comment by ababushkin-bscmsc** [comment]
I tried the command "go mod download", no results.
what dependencies do I need for ios remote provider? You can find out the requirements for your project

**Comment by nanoscopic** [comment]
This should be corrected now. I ran `go mod tidy` and `go get` for the ujsonin project and committed the results, so these problems should no longer occur. You may also run `go mod tidy` and `go get` on the provider itself, which may help as well...
