### ISSUE TITLE
Error while using make cmd in ios_remote_provider after setup the config.json

### ISSUE THREAD

**Issue by sonusainier** [nanoscopic/ios_remote_provider#22]
rohitsaini@Rohits-MacBook-Pro ios_remote_provider % make
go build -o main -tags macos .
go: github.com/elastic/go-sysinfo@v1.5.0: missing go.sum entry; to add it:
        go mod download github.com/elastic/go-sysinfo
make: *** [main] Error 1
rohitsaini@Rohits-MacBook-Pro ios_remote_provider %

**Comment by nanoscopic** [comment]
This will be addressed in the next commit / update. For now just run `go mod tidy`, then `go get`, then rerun `make` and it should be resolved.

This is golang being golang, and I don't consider it a fault of the project... As I said though, do as stated and it will work, and it will be resolved in the next commit.
