### ISSUE TITLE
Automatically starting Video App is not working 

### ISSUE THREAD

**Issue by sonusainier** [nanoscopic/ios_remote_provider#23]
{
    ...
    devices:[
        {
            udid:"328d2fc4e39a54c86a81671b4f901b23ab503f"
            uiWidth:375
            uiHeight:675
            // bottomUp or topDown
            controlCenterMethod:"bottomUp"
        }
    ]
}

i have this device info in config.json insise ios_remote_provider but when i start ./main run cmd nothing happened 
i have to start manually but i want to start it automatically whenever the session start
also can we remove the red bar from top of mobile screen is it possible??

**Comment by nanoscopic** [comment]
The latest changes from today should help make this work a bit more stably. What is the model of the device you are using?

You cannot remove the red bar. It is enforced by how iOS works for upload broadcast extension apps.

There are other ways to get video, such as MJPEG from WDA, which I will add support for, that don't require the red bar, but the performance is worse than using the app method that has the red bar.

I have considered faking out the video and just hiding the red color, but that doesn't really accomplish much. Others also dislike the red bar but I'm not entirely clear why it matters at all if the bar is red.

**Comment by nanoscopic** [comment]
The various problems with this should be fixed now. Make sure to update your video app.
