### ISSUE TITLE
Please provide proper documentation according to new changes 

### ISSUE THREAD

**Issue by sonusainier** [nanoscopic/ios_remote_provider#27]

**Comment by nanoscopic** [comment]
Agreed that I should / need to update the documentation.

That said the new changes should still work according to the old documentation.

The main change is that the video app has been renamed, so the video app needs to be updated in tandem with the new changes to the provider.

If you have a specific problem with the new changes that you are unclear on you should say what that is so I can address that. This ticket as is is quite vague.

**Comment by nanoscopic** [comment]
Documentation has been updated some to matches new changes. Please specify what sort of documentation info is missing when creating a future ticket.
