### ISSUE TITLE
WARN while starting ios_remote_provider

### ISSUE THREAD

**Issue by sonusainier** [nanoscopic/ios_remote_provider#28]
WARN[0000] Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
%!s(MISSING) is not set in either config.json or default.json%

**Comment by nanoscopic** [comment]
The warning is correct / intentional.

The calculated.json file is needed in order to use tidevice. Tidevice is the new/best way to start WDA currently with provider.

The second part of that warning though is messed up. It shouldn't have the "%!s(MISSING)" bit. I will look at and adjust it.

I suppose I can hide the warning if tidevice is not configured to be used. I agree that the warning will confuse others.

**Comment by sonusainier** [comment]
what should i do in order to run the the provider

**Comment by sonusainier** [comment]
Warning is resolved after running "make usetidevice" cmd but still not able to run the provider

%!s(MISSING) is not set in either config.json or default.json%

**Comment by sonusainier** [comment]
func GetStr( root uj.JNode, path string ) string {
    node := root.Get( path )
    if node == nil {
        fmt.Fprintf( os.Stderr, "%s is not set in either config.json or default.json" )
        os.Exit(1)
    }
    return node.String()
}
func GetBool( root uj.JNode, path string ) bool {
    node := root.Get( path )
    if node == nil {
        fmt.Fprintf( os.Stderr, "%s is not set in either config.json or default.json" )
        os.Exit(1)
    }
    return node.Bool()
}
func GetInt( root uj.JNode, path string ) int {
    node := root.Get( path )
    if node == nil {
        fmt.Fprintf( os.Stderr, "%s is not set in either config.json or default.json" )
        os.Exit(1)
    }
    return node.Int()
}

**Comment by sonusainier** [comment]
Please suggest something ??

**Comment by chewbacca70** [comment]
Same issue here when ./main register
%!s(MISSING) is not set in either config.json or default.json%

**Comment by aslozhkin** [comment]
i renamed vidtest to vidapp in config.json and it works

**Comment by kristeedev** [comment]
`pip3 install tidevice` and to fix the first error. And do `make usetidevice`.

**Comment by chewbacca70** [comment]
thanks @aslozhkin ! Changing to vidapp in config.json did the trick

**Comment by nanoscopic** [comment]
My bad on forgetting to commit the new change to config.json

I always avoid committing it because I have my own config changes for my setup of course.

I will correct this for other new users.

Great job on figuring this out amongst yourself before I noticed and explained.

**Comment by nanoscopic** [comment]
Config.json file has been updated.
