### ISSUE TITLE
Installed CF Vidstream app is version 1.0; must be version 1.1

### ISSUE THREAD

**Issue by chewbacca70** [nanoscopic/ios_remote_provider#31]
Hi,
I ran into this issue:
```
Notified control floor of 'wda stop'; uuid=***9182
WARN[0002] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9182
Installed CF Vidstream app is version 1.0; must be version 1.1
panic: Wrong vidstream version
```

I fixed it by setting the "Bundle Version String" in the Info TAB to 1.1

![Screenshot 2021-06-18 at 10 44 02](https://user-images.githubusercontent.com/84956095/122533675-1ed9fc80-d022-11eb-9160-ef81bc87b6f7.png)

So it would be great to fix that also in Vidapp repo.

After that Stream opens automatically. Well done :-)

But I am still not able to make 2 devices connected on one mashine controllable .

Cheers 
Chubbi

**Comment by nanoscopic** [comment]
Updated.
