### ISSUE TITLE
video app wont start automatically on the second connected device

### ISSUE THREAD

**Issue by chewbacca70** [nanoscopic/ios_remote_provider#33]
HI @nanoscopic 
Thank you very much for fixing #21 I can control 2 devices now on my machine.

![image](https://user-images.githubusercontent.com/84956095/123219885-ac5b9780-d4cd-11eb-8ee4-8f522735f300.png)

If I start the provider via ./main run the calls to start WDA working now for 2 devices. But the video app will be started automatically only on the first device. On the second device the video app wont be started. If I start the video stream manually before starting the provider on the second device I can control 2 devices perfectly.

Maybe it is simply missing to start also on all devices.
Pls. find the provider logs. It shows that it simply wont got to the start video app routine I guess.

Device 1:
`INFO[0003] [WDA] successfully started                    port=8102 proc=wda type=wda_start uuid="***0fc7"
INFO[0003] [WDA] successfully started                    port=8102 type=wda_start udid="***0fc7"
Notified control floor of 'wda start'; uuid=***0fc7
Finding element named   Broadcast Selector
Posting to http://127.0.0.1:8102/session/7E9AF8CE-381A-4B67-A5C6-1525F4E5566E/element
Result: {
  "value" : {
    "ELEMENT" : "04000000-0000-0000-A601-000000000000",
    "element-6066-11e4-a52e-4f735466cecf" : "04000000-0000-0000-A601-000000000000"
  },
  "sessionId" : "7E9AF8CE-381A-4B67-A5C6-1525F4E5566E"
}
Posting to http://127.0.0.1:8102/session/7E9AF8CE-381A-4B67-A5C6-1525F4E5566E/element/04000000-0000-0000-A601-000000000000/click
Result: {
  "value" : null,
  "sessionId" : "7E9AF8CE-381A-4B67-A5C6-1525F4E5566E"
}
Finding element named Start Broadcast
Posting to http://127.0.0.1:8102/session/7E9AF8CE-381A-4B67-A5C6-1525F4E5566E/element
Result: {
  "value" : {
    "ELEMENT" : "F7000000-0000-0000-3900-000000000000",
    "element-6066-11e4-a52e-4f735466cecf" : "F7000000-0000-0000-3900-000000000000"
  },
  "sessionId" : "7E9AF8CE-381A-4B67-A5C6-1525F4E5566E"
}
Posting to http://127.0.0.1:8102/session/7E9AF8CE-381A-4B67-A5C6-1525F4E5566E/element/F7000000-0000-0000-3900-000000000000/click
Result: {
  "value" : null,
  "sessionId" : "7E9AF8CE-381A-4B67-A5C6-1525F4E5566E"
}
id = dc490c9beb4c3423b1102678f57eab21d2c20fc7

and for the second device:
`INFO[0022] [WDA] successfully started                    port=8106 proc=wda type=wda_start uuid="***131b"
INFO[0022] [WDA] successfully started                    port=8106 type=wda_start udid="***131b"
Notified control floor of 'wda start'; uuid=***131b
Got incoming frame 120
Got incoming frame 150
Got incoming frame 180
Got incoming frame 210
Got incoming frame 240
Got incoming frame 270
Got incoming frame 300
Got incoming frame 330
Got incoming frame 360
Got incoming frame 390
Got incoming frame 420
Failed to connect video app control 5 times. Giving up.Got incoming frame 450
Got incoming frame 480
Got incoming frame 510

`

**Comment by nanoscopic** [comment]
Fixed.
