### ISSUE TITLE
Error adding reservation

### ISSUE THREAD

**Issue by aslozhkin** [nanoscopic/ios_remote_provider#34]
Hi, after click "Device video" get the error: "Error adding reservation: no such table: reservartion"
![image](https://user-images.githubusercontent.com/73738339/123242685-f56e1480-d4ea-11eb-8c15-0ec3d73e8ec9.png)
Sorry that created the issue not in CF. 😒

**Comment by sonusainier** [comment]
Same here 
provider start but got Error adding reservation: no such table: reservation

**Comment by chewbacca70** [comment]
which user did you specified in config.json 
I can remember some trouble when not using username "first", as user "first" was hardcoded somewhere... but I can't remember. I managed to make it work with specifying "first"

maybe it helps

`{
    controlfloor: {
        host: "xxx"
        username: "first"
        https: true
        selfSigned: true
    }

`

**Comment by nanoscopic** [comment]
The DB schema has changed. Right now there is no detection that a change has been made and automatic update of the DB that was already made.

Solution is to just delete `db.sqlite3` and restart; the DB will be recreated with the new schema then.

--

As far as the username of "first" goes; that username just identifies a specific provider. It can be anything.

The password used to register a provider to CF is global and is not unique to a specific user. It is a "registration password".

**Comment by sonusainier** [comment]
Thanks it is working after deleting the db.sqlite3 from CF

**Comment by aslozhkin** [comment]
Thank you! It works
