### ISSUE TITLE
swipe makes wda become not responsive

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#40]
Hi,

If I do a swipe by opening an app that does not have a swipe screen, the wda becomes unresponsive for a long time, and in fact, it just freezes.

**Steps to reproduce:**
1 - Open notes app
2 - do a random swipe on the screen
3 - click on home or try to do any other operation, nothing works.

**Expected:**
I did swipe nothing happened, if I click on the home button it should return to the home screen

**Actual:**
Just freezes on the notes app and not letting me perform any other action

**Logs:**
provider.log - https://gist.github.com/sai-tirunagiri/1cc02c173b778f6dcf90c614c34ed8d6

**Comment by nanoscopic** [comment]
I was able to duplicate this behavior. This is an underlying problem with WDA. Will have to research to see if there is some easy way to fix this.

Essentially, if you call swipe in WDA, it just hangs. It certainly should not do that.

**Comment by sai-tirunagiri** [comment]
I was curious about why this happens, so I got into it, and here is what I did,

* Tested this by using appium webdriveragent to see if I end up getting the same issue. But I did not get this issue! if I do a swipe on the app screen which does not have a swipe, the wda responds back with 200 and value "null".
* thought it has something that got to do with webdriveragent being few commits back compared to appium/webdriveragent repo.
* so, I cloned the webdriveragent from appium repository, added the changes which were in nanoscopic/webdriveragent (only the changed code without replacing the entire code ).
* But the above step didn't work.
* I noticed a difference between appium and our setup, on appium the webdriveragent is started with XCTest using xcodebuild command and we use tidevice to start the wda.
* finally, when I started the wda using tidevice with xctest instead of wdaproxy it started working. I tested by doing the below which is working.

**command which is working**
```
tidevice xctest -B com.appium.WebDriverAgentRunner.xctrunner
```

**Expected API Call response:**
```
http://192.168.1.47:8100/session/52A7B2AA-3103-48B3-9CC5-6797AC4D543F/wda/touch/perform
{
    "value": null,
    "sessionId": "52A7B2AA-3103-48B3-9CC5-6797AC4D543F"
}
```

**command which is not working**
```
tidevice wdaproxy -B com.appium.WebDriverAgentRunner.xctrunner -p 0
```
**tidevice.log**
```
[D 210708 15:40:26 _wdaproxy:118] [****4bbe] launch WDA
[I 210708 15:40:26 _device:960] BundleID: com.appium.WebDriverAgentRunner.xctrunner
[I 210708 15:40:26 _device:963] ProductVersion: 14.4.1
[I 210708 15:40:26 _device:965] DeviceIdentifier: ****4bbe
[I 210708 15:40:27 _device:804] SignIdentity: 'Apple Development: Ameet Deshpande (9RR6H967DA)'
[I 210708 15:40:27 _device:810] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 210708 15:40:27 _device:841] AppContainer: /private/var/mobile/Containers/Data/Application/3ECE6336-7241-4E15-806C-C9CA76CAF046
[I 210708 15:40:27 _device:881] Launch 'com.appium.WebDriverAgentRunner.xctrunner' pid: 16212
[I 210708 15:40:27 _device:1014] Test runner ready detected
[I 210708 15:40:27 _device:1006] Start execute test plan with IDE version: 29
[I 210708 15:40:27 _device:917] WebDriverAgent start successfully
**[D 210708 15:41:31 _wdaproxy:93] [****4bbe] WDA is not response, check again after 10s
[I 210708 15:41:44 _wdaproxy:97] [****4bbe] WDA confirmed not running
[I 210708 15:41:44 _wdaproxy:106] [****4bbe] WDA keeper stopped
[I 210708 15:41:44 _wdaproxy:145] [****4bbe] WDA stopped for the 1st time,** running 1.3 minutes
```

so, @nanoscopic what is your opinion on this finding.

Thanks.

**Comment by nanoscopic** [comment]
The new swipe methodology does not have this problem. On screens that have no swipe support where you swipe, now when you do so simply nothing happens.
