### ISSUE TITLE
Issues starting WDA

### ISSUE THREAD

**Issue by kpalczewski** [nanoscopic/ios_remote_provider#43]
Hi. I am starting ios_remote_provider with command
`./main run`

I am able to see video using ControlFloor, but I cannot control the device.

In terminal I get this error from ios remote provider:
```
INFO[0001] Process start - backupVideo                   binary=bin/iosif id=00008030-0004686011EB802E port=8105 proc=backupVideo type=proc_start
INFO[0001] Process start - tunnel_8102->8100_8106->8150  binary=bin/iosif proc="tunnel_8102->8100_8106->8150" type=proc_start
INFO[0002] Process start - wda                           binary=/ proc=wda type=proc_start
ERRO[0002] Error starting - wda                          error="exec: \"/\": permission denied" proc=wda type=proc_err
id = 00008030-0004686011EB802E
Starting bin/iosif with [tunnel -id 00008030-0004686011EB802E 8103:8352 8104:8351]
INFO[0002] Process start - syslogMonitor                 binary=bin/iosif id=00008030-0004686011EB802E proc=syslogMonitor type=proc_start
INFO[0002] Process start - tunnel_8103->8352_8104->8351  binary=bin/iosif proc="tunnel_8103->8352_8104->8351" type=proc_start
Connected to control port
Attempting to connect to video
Connected to video port
Main loop start
FIRSTFRAME{"type":"frame1","width":562,"height":1000,"uuid":"00008030-0004686011EB802E"}
Notified control floor of 'video start'; uuid=***802E
INFO[0002] Video - first frame                           height=0 proc=ios_video_stream type=first_frame udid="***802E" width=0
```

has anyone encountered such issue?
I don't seem to be able to install and start wda on my device.

**Comment by sonusainier** [comment]
wda is not starting after after running **./main run** cmd 

- Sending SIGTERM              pid=5264 proc=iosif type=proc_cleanup
INFO[0001] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
Location from redirect of controlfloor login:'https://localhost:8080/provider/'
Logged in to control floor
self signed option
link for dialer = wss://localhost:8080/provider/ws
Creating IIFDev with udid=328d2fc4e39a54c86a81671b4f901b23ab50379f
udid: 328d2fc4e39a54c86a81671b4f901b23ab50379f
Running bin/iosif [mg -json -id 328d2fc4e39a54c86a81671b4f901b23ab50379f AvailableDisplayZoomSizes main-screen-width main-screen-height ArtworkTraits]
json:{
"AvailableDisplayZoomSizes":{
  default:[
    2
    375
    2
    667
  ]
  zoomed:[
    2
    320
    2
    568
  ]
}
,
"main-screen-width":750
,
"main-screen-height":1334
,
"ArtworkTraits":{
  ArtworkDeviceIdiom:"phone"
  ArtworkDeviceSubType:569
  CompatibleDeviceFallback:"iPhone8,1"
  GraphicsFeatureSetFallbacks:"APPLE3v1:APPLE2:APPLE1:GLES2,0"
  ArtworkDisplayGamut:"P3"
  ArtworkDeviceProductDescription:"iPhone 7"
  ArtworkDynamicDisplayMode:"0"
  GraphicsFeatureSetClass:"APPLE3"
  ArtworkDeviceScaleFactor:2
  DevicePerformanceMemoryClass:2
}

}

Notified control floor of 'device existence'; uuid=***379f
udid for info: 328d2fc4e39a54c86a81671b4f901b23ab50379f
json:{
DeviceName:"iPhone"
,
EthernetAddress:"70:f0:87:c1:24:c1"
,
ModelNumber:"MN8X2"
,
HardwareModel:"D101AP"
,
PhoneNumber:"+91 870-8584615"
,
ProductType:"iPhone9,3"
,
ProductVersion:"15.0"
,
UniqueDeviceID:"328d2fc4e39a54c86a81671b4f901b23ab50379f"
,
InternationalMobileEquipmentIdentity:"355334082574330"
,
}

mapped result:map[DeviceName:iPhone EthernetAddress:70:f0:87:c1:24:c1 HardwareModel:D101AP InternationalMobileEquipmentIdentity:355334082574330 ModelNumber:MN8X2 PhoneNumber:+91 870-8584615 ProductType:iPhone9,3 ProductVersion:15.0 UniqueDeviceID:328d2fc4e39a54c86a81671b4f901b23ab50379f]
INFO[0001] Device Info                                   info="map[DeviceName:iPhone EthernetAddress:70:f0:87:c1:24:c1 HardwareModel:D101AP InternationalMobileEquipmentIdentity:355334082574330 ModelNumber:MN8X2 PhoneNumber:+91 870-8584615 ProductType:iPhone9,3 ProductVersion:15.0 UniqueDeviceID:328d2fc4e39a54c86a81671b4f901b23ab50379f]" type=devInfo uuid="***379f"
Notified control floor of 'device info'; uuid=***379f
Starting bin/iosif with [tunnel -id 328d2fc4e39a54c86a81671b4f901b23ab50379f 8102:8100 8106:8150]
port = 8105
id = 328d2fc4e39a54c86a81671b4f901b23ab50379f
INFO[0001] Process start - tunnel_8102->8100_8106->8150  binary=bin/iosif proc="tunnel_8102->8100_8106->8150" type=proc_start
INFO[0001] Process start - backupVideo                   binary=bin/iosif id=328d2fc4e39a54c86a81671b4f901b23ab50379f port=8105 proc=backupVideo type=proc_start
INFO[0001] Process start - wda                           binary=/usr/local/lib/python3.9/site-packages/../../../bin/tidevice proc=wda type=proc_start
Error on Some Service: kAMDInvalidServiceError - The service is invalid.
Error on Receive Intro: kAMDInvalidArgumentError - The argument is invalid.
Error on Accept Version: kAMDInvalidArgumentError - The argument is invalid.
Error on Receive Version Accept: kAMDInvalidArgumentError - The argument is invalid.
WARN[0002] Process end - wda                             proc=wda type=proc_end
INFO[0002] Process start - wda                           binary=/usr/local/lib/python3.9/site-packages/../../../bin/tidevice proc=wda type=proc_start
Notified control floor of 'wda stop'; uuid=***379f
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52296->127.0.0.1:8102: read: connection reset by peer
  Retrying
WARN[0002] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***379f
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52300->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52301->127.0.0.1:8102: read: connection reset by peer
  Retrying
INFO[0004] Process start - wda                           binary=/usr/local/lib/python3.9/site-packages/../../../bin/tidevice proc=wda type=proc_start
WARN[0005] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***379f
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52304->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52305->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52306->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52307->127.0.0.1:8102: read: connection reset by peer
  Retrying
INFO[0010] Process start - wda                           binary=/usr/local/lib/python3.9/site-packages/../../../bin/tidevice proc=wda type=proc_start
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52309->127.0.0.1:8102: read: connection reset by peer
  Retrying
WARN[0010] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***379f
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52312->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52313->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52314->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52315->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52316->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52317->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52318->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52319->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:52320->127.0.0.1:8102: read: connection reset by peer
  Retrying

**Comment by nanoscopic** [comment]
You state "I am unable to install WDA on my device". What do you mean by this?

The Makefile in ios_remote_provider does build the required fork of WDA, but that built WDA must be installed to the device before it can be used.

Double checking the README, it is, though, missing the needed instruction explaining how to install WDA. I will add it.

What have you done, if anything, to install WDA to your device?

**Comment by kpalczewski** [comment]
@nanoscopic I was able to install WDA on my device. I forgot that Xcode uploads it only when you click Product -> Test

after couple of restarts of ControlFloor and ios remote provider it started to work.
Strangely 
`ERRO[0002] Error starting - wda                          error="exec: \"/\": permission denied" proc=wda type=proc_err
id = 00008030-0004686011EB802E`
is still there. In Control Floor website there is still
`WDA Status | down
`
in device's details. Maybe something is still badly configured on my part :(

**Comment by nanoscopic** [comment]
Depending on how you have configured, the provider will use either go-ios or tidevice to start WDA. Right now I'd reccomend using tidevice. See the wiki for instructions. You need to install tidevice, then run `make usetidevice` to figure out the path to tidevice on your system.

If you haven't run the `make usetidevice` and have it configured to use tidevice, it will output the above error because it doesn't have the path to know where tidevice is located to run it.

**Comment by nanoscopic** [comment]
With the new changes to WDA, an issue starting WDA with tidevice has been introduced. For now go-ios works to start WDA, but only works on some devices ( doesn't work on iPhone 7 for example )

**Comment by nanoscopic** [comment]
Am closing this issue in favor of starting a new one to track the current problem starting WDA. The errors occurring in this issue have been resolved.
