### ISSUE TITLE
Swiping breaks provider

### ISSUE THREAD

**Issue by kristeedev** [nanoscopic/ios_remote_provider#5]
Hi @nanoscopic sir,

Noted that the provider breaks during swiping.
panic: runtime error: index out of range [0] with length 0

Attached the error.

goroutine 47 [running]:

main.(*IIFDev).NewSyslogMonitor.func1(0x0, 0x0, 0xc00014e310)

        ios_remote_provider/bridge_iif.go:304 +0x43c

main.proc_generic.func1(0xc00014e310, 0xc000118780, 0xc000126280, 0xc000118690, 0xc000118750, 0xc000140420, 0xc00011c1e0, 0x0, 0x0)

        ios_remote_provider/proc_generic.go:183 +0xc4e

created by main.proc_generic

        ios_remote_provider/proc_generic.go:105 +0x626

**Comment by nanoscopic** [comment]
The line of code in question erroring out is one checking the first character of a line of output coming from `iosif log`. This indicates that an empty string was sent as a line of output. That doesn't make a lot of sense... I'd recommend deleting `repos/iosif/iosif`, pulling iosif in case it didn't automatically get pulled: `cd repos/iosif; git pull`, and then running `make` to rebuild iosif in case it is an issue with iosif not automatically getting rebuilt to be the latest version.

**Comment by kristeedev** [comment]
Removed old `iosif`, pulled latest from git and rebuilt by running`make`. Recompiled provider to make sure if that is also the latest. The binary still breaks at this point while doing a swipe:

panic: runtime error: index out of range [0] with length 0

goroutine 44 [running]:
main.(*IIFDev).NewSyslogMonitor.func1(0x0, 0x0, 0xc0000f6150)
        ios_remote_provider/bridge_iif.go:304 +0x43c
main.proc_generic.func1(0xc0000f6150, 0xc00009e8d0, 0xc0000ac200, 0xc00009e810, 0xc00009e8a0, 0xc0000c6360, 0xc0000a21f0, 0x0, 0x0)
        ios_remote_provider/proc_generic.go:183 +0xc4e
created by main.proc_generic
        ios_remote_provider/proc_generic.go:105 +0x626

**Comment by kristeedev** [comment]
`if line[0] == '*' {`

We should add a check to check if line array is empty. Line 304.

**Comment by ahmetdellall** [comment]
greetings sir @kristeedev  Are there any developments in this regard? I have the same problem with all the iOS devices I connect to. I tried in the solution mentioned above.

@kristeedev  Although I add a check, it still stops working. If you have a solution, I would like to try it.

**Comment by sai-tirunagiri** [comment]
same error, any fix for this.

```
Tunnel stopped
Tunnel stopped

WARN[0021] Process end - device_trigger                  proc=device_trigger type=proc_end
INFO[0021] device trigger stopped
INFO[0021] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
WARN[0021] Process end - backupVideo                     proc=backupVideo type=proc_end
INFO[0021] Process start - backupVideo                   binary=bin/iosif id=5126be31cfff436356a1627c09c9268136513a67 port=8105 proc=backupVideo type=proc_start
INFO[0021]                                               iserr=true line= proc=syslogMonitor
INFO[0021]                                               iserr=true line= proc=syslogMonitor
INFO[0021]                                               iserr=true line= proc=syslogMonitor
INFO[0021]                                               iserr=true line= proc=syslogMonitor
WARN[0021] Process end - syslogMonitor                   proc=syslogMonitor type=proc_end
INFO[0021] Process start - syslogMonitor                 binary=bin/iosif id=5126be31cfff436356a1627c09c9268136513a67 proc=syslogMonitor type=proc_start
Pipe action 2
Pipe action 2
INFO[0021] Swiping:71 468 265 467
Posting to http://127.0.0.1:8102/session/2E874326-6FC8-4EC6-B647-2814F5B7A0BC/wda/touch/perform
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x433d526]

goroutine 49 [running]:
main.resp_to_str(0x0, 0x54, 0x446cfc0)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/wda.go:167 +0x26
main.resp_to_val(0x0, 0xc0002f6060, 0x54)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/wda.go:177 +0x2f
main.(*WDA).sessionCall(0xc00032c1c0, 0x43fc5fe, 0x12, 0xc0002b2000, 0x19c, 0xc0002b2000, 0x19c)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/wda.go:241 +0x1da
main.(*WDA).swipe(0xc00032c1c0, 0x47, 0x1d4, 0x109, 0x1d3)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/wda.go:369 +0x2a9
main.(*Device).swipe(...)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/device.go:340
main.(*ControlFloor).openWebsocket.func6(0xc0000f8580, 0xc0000ae060, 0x28, 0x47, 0x1d4, 0x109, 0x1d3)
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/controlfloor.go:285 +0xa7
created by main.(*ControlFloor).openWebsocket
	/Users/saiprasadt/Desktop/nanoscopic-latest/ios_remote_provider/controlfloor.go:282 +0x9d8
```

**Comment by nanoscopic** [comment]
This was addressed a while back and is no longer an issue.
