### ISSUE TITLE
ios_remote_provider ERROR: io.ReadAll 

### ISSUE THREAD

**Issue by aslozhkin** [nanoscopic/ios_remote_provider#51]
ios_remote_provider % **make**
og:
go build -o main -tags macos .
git clone "https://github.com/nanoscopic/iosif.git" repos/iosif
Cloning into 'repos/iosif'...
remote: Enumerating objects: 252, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 252 (delta 123), reused 213 (delta 87), pack-reused 0
Receiving objects: 100% (252/252), 193.84 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (123/123), done.
cd repos/iosif && git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
touch repos/iosif/versionMarker
make -C repos/iosif
gcc -g -I /usr/local/include -o iosif bytearr.c cfutil.c channel.c cmd_bytetest.c cmd_dtxdump.c cmd_file.c cmd_gg.c cmd_image.c cmd_info.c cmd_install.c cmd_ioreg.c cmd_list.c cmd_listapps.c cmd_mg.c cmd_process.c cmd_syscfg.c cmd_syslog.c cmd_tunnel.c dtxmsg.c main.c mobdev_err.c service.c service_deviceinfo.c service_notifications.c service_sysmon.c service_testmanager.c services.c uclop.c uuid.c archiver/archiver.c archiver/byteswap.c archiver/lz4.c archiver/plist.c archiver/plist_read.c archiver/ptrarr.c archiver/unarchiver.c ujsonin/red_black_tree.c ujsonin/string-tree.c ujsonin/ujsonin.c sandbird/sandbird.c -F ./ -framework CoreFoundation -framework MobileDevice
touch bin/iosif
git clone "https://github.com/nanoscopic/ios_video_app.git" repos/vidapp
Cloning into 'repos/vidapp'...
remote: Enumerating objects: 229, done.
remote: Counting objects: 100% (229/229), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 229 (delta 90), reused 207 (delta 68), pack-reused 0
Receiving objects: 100% (229/229), 6.72 MiB | 4.80 MiB/s, done.
Resolving deltas: 100% (90/90), done.
cd repos/vidapp && git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
touch repos/vidapp/versionMarker
git clone "https://github.com/nanoscopic/go-ios.git" repos/go-ios
Cloning into 'repos/go-ios'...
remote: Enumerating objects: 732, done.
remote: Counting objects: 100% (324/324), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 732 (delta 214), reused 158 (delta 146), pack-reused 408
Receiving objects: 100% (732/732), 773.23 KiB | 2.88 MiB/s, done.
Resolving deltas: 100% (369/369), done.
cd repos/go-ios && git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
touch repos/go-ios/versionMarker
cd repos/go-ios && go build .
\# github.com/danielpaulus/go-ios/ios/imagemounter
ios/imagemounter/imagemounter.go:155:25: undefined: io.ReadAll
make: *** [bin/go-ios] Error 2

**Comment by chewbacca70** [comment]
Hi,
you need to update go version to 1.16, see closed issue #49
