### ISSUE TITLE
ios_remote_provider make ERROR

### ISSUE THREAD

**Issue by mcloudfarm** [nanoscopic/ios_remote_provider#53]
HEAD detached at b8e149b

mcloud@Mac-mini % go version
go version go1.16.6 darwin/amd64

mcloud@Mac-mini % make                                         
go build -o main -tags macos .
proc_generic.go:6:5: missing go.sum entry for module providing package github.com/go-cmd/cmd (imported by main.go); to add:
	go get main.go
controlfloor.go:20:5: missing go.sum entry for module providing package github.com/gorilla/websocket (imported by main.go); to add:
	go get main.go
../go/pkg/mod/github.com/elastic/go-sysinfo@v1.5.0/providers/darwin/host_darwin_amd64.go:26:2: missing go.sum entry for module providing package github.com/joeshaw/multierror (imported by github.com/elastic/go-sysinfo/providers/darwin); to add:
	go get github.com/elastic/go-sysinfo/providers/darwin@v1.5.0
main.go:10:5: missing go.sum entry for module providing package github.com/nanoscopic/uclop/mod (imported by main.go); to add:
	go get main.go
bridge_iif.go:10:5: missing go.sum entry for module providing package github.com/nanoscopic/ujsonin/v2/mod (imported by main.go); to add:
	go get main.go
bridge_iif.go:12:5: missing go.sum entry for module providing package github.com/nfnt/resize (imported by main.go); to add:
	go get main.go
../go/pkg/mod/github.com/elastic/go-sysinfo@v1.5.0/types/errors.go:20:8: missing go.sum entry for module providing package github.com/pkg/errors (imported by github.com/elastic/go-sysinfo/internal/registry); to add:
	go get github.com/elastic/go-sysinfo/internal/registry@v1.5.0
bridge_iif.go:11:5: missing go.sum entry for module providing package github.com/sirupsen/logrus (imported by main.go); to add:
	go get main.go
video_app_stream.go:8:5: missing go.sum entry for module providing package go.nanomsg.org/mangos/v3 (imported by main.go); to add:
	go get main.go
video_app_stream.go:9:5: missing go.sum entry for module providing package go.nanomsg.org/mangos/v3/protocol/pull (imported by main.go); to add:
	go get main.go
video_app_stream.go:10:5: missing go.sum entry for module providing package go.nanomsg.org/mangos/v3/protocol/req (imported by main.go); to add:
	go get main.go
video_app_stream.go:13:5: missing go.sum entry for module providing package go.nanomsg.org/mangos/v3/transport/all (imported by main.go); to add:
	go get main.go
../go/pkg/mod/github.com/elastic/go-sysinfo@v1.5.0/providers/darwin/os.go:26:2: missing go.sum entry for module providing package howett.net/plist (imported by github.com/elastic/go-sysinfo/providers/darwin); to add:
	go get github.com/elastic/go-sysinfo/providers/darwin@v1.5.0
make: *** [main] Error 1

**Comment by chewbacca70** [comment]
make sure you run go1.16 version and execute `make go.sum` then `make`
