### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference while getting AlertInfo

### ISSUE THREAD

**Issue by s4ib0t87** [nanoscopic/ios_remote_provider#56]
Hi, after updating to the latest version of CF and ios_remote_provider I get an runtime error when starting the remote_provider. 

``
INFO Created WDA session                           id=D59C2424-1FB5-4415-B588-7183157EBF97 type=wda_session_created
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x435151b]

goroutine 28 [running]:
main.(*WDA).AlertInfo(0xc0001663f0, 0xc00002a480, 0x23, 0xc0001e6030, 0x24)
        /opt/ios_remote_provider/wda.go:520 +0xdb
main.(*WDA).StartBroadcastStream(0xc0001663f0, 0xc000130990, 0xc, 0xc00002a480, 0x23)
        /opt/ios_remote_provider/wda.go:538 +0x156
main.(*Device).enableVideo(0xc000292580)
        /opt/ios_remote_provider/device.go:445 +0x331
main.(*Device).onWdaReady.func1()
        /opt/ios_remote_provider/device.go:182 +0x2f
main.(*GIDev).tunnel(0xc0000301c0, 0xc00033c720, 0x3, 0x3, 0xc0001e1770)
        /opt/ios_remote_provider/bridge_goios.go:142 +0x152
main.(*Device).forwardVidPorts(0xc000292580, 0xc00002e100, 0x19, 0xc0001e1770)
        /opt/ios_remote_provider/device.go:517 +0xa6
main.(*Device).onWdaReady(0xc000292580)
        /opt/ios_remote_provider/device.go:181 +0x1aa
main.(*Device).startEventLoop.func1(0xc000292580)
        /opt/ios_remote_provider/device.go:198 +0x64c
created by main.(*Device).startEventLoop
        /opt/ios_remote_provider/device.go:189 +0x3f
``

Thanks in advance.

**Comment by nanoscopic** [comment]
My bad. I forgot I added a call to WDA. I have committed and pushed the updated to WebDriverAgent now and incremented the version marker.

You will need to rebuild and redeploy WDA.

The update enables the new alert auto-response feature making it possible for provider to auto-dismiss blocking alerts that would otherwise prevent automatic startup of the video app.
