### ISSUE TITLE
Remove nng dependency

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#6]
@nanoscopic - Hi, I am getting into an issue while doing a command "make" on ios_remote_provider,

```
saiprasadt@LPT1058-B1s-MacBook-Pro ios_remote_provider % make all
make -C repos/iosif
gcc -DNNG -lnng -I /usr/local/include -o iosif bytearr.c cfutil.c channel.c cmd_bytetest.c cmd_gg.c cmd_image.c cmd_info.c cmd_install.c cmd_ioreg.c cmd_list.c cmd_listapps.c cmd_mg.c cmd_syscfg.c cmd_syslog.c cmd_tunnel.c dtxmsg.c main.c mobdev_err.c service.c service_deviceinfo.c service_notifications.c service_sysmon.c service_testmanager.c services.c uclop.c archiver/archiver.c archiver/unarchiver.c archiver/byteswap.c archiver/lz4.c -F ./ -framework CoreFoundation -framework MobileDevice
ld: library not found for -lnng
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [iosif] Error 1
make: *** [bin/iosif] Error 2
```
What could be the possible issue

**Comment by nanoscopic** [comment]
The latest round of changes introduced nng ( Nanomsg Next Gen ) as a dependency for iosif. You need to install it; on MacOS: `brew install nng`

I will likely alter the code to also remove this dependency in the near future, to remove the need to have it installed, but for now it is needed.

**Comment by kristeedev** [comment]
Suggest to build nng separately.
https://github.com/nanomsg/nng
`cd nng`
`mkdir build`
`cmake -G build/         #you may need to install cmake for this`
`make`
`make install`

**Comment by nanoscopic** [comment]
nng is no longer a dependency of iosif
