### ISSUE TITLE
Segmentation violation issue with "main run" using tidevice mode

### ISSUE THREAD

**Issue by ngtrphuong** [nanoscopic/ios_remote_provider#60]
I can finished buidling controlfloor, run it fine,

The same for nng

However, with ios_remote_provider repo building, I failed with step 5 below - 

Step 1: **make usetidevice** successful

Step 2: **make wda** successful

Step 3: Ran **make** successful

Step 4: Register real device successful with command ** ./main register **

` ============================
root@MAC-Big-Sur-2 ios_remote_provider % ./main register

Enter registration password:

Using default registration password of doreg

Registered and got password 85d19b87b8dad6d909c614167a7c257f

User first existed so password was renewed

root@MAC-Big-Sur-2 ios_remote_provider %

`============================

Step 5: I failed in this step with command **./main run**

Console shows segmentation error as log below - 

`============================
root@MAC-Big-Sur-2 ios_remote_provider % ./main run
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20358cbe]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20358cbe
stack: frame={sp:0x7000015bce58, fp:0x7000015bcea8} stack=[0x70000153d338,0x7000015bcf38)
0x00007000015bcd58:  0x01007000015bcd78  0x0000000000000004
0x00007000015bcd68:  0x000000000000001f  0x00007fff20358cbe
0x00007000015bcd78:  0x0b01dfacedebac1e  0x0000000000000001
0x00007000015bcd88:  0x00000000040367b1 <runtime.throw+0x0000000000000071>  0x00007000015bce28
0x00007000015bcd98:  0x0000000004380186  0x00007000015bcde0
0x00007000015bcda8:  0x0000000004036a68 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000c000000ea0
0x00007000015bcdb8:  0x0000000000000001  0x0000000000000001
0x00007000015bcdc8:  0x00007000015bce28  0x00000000040367b1 <runtime.throw+0x0000000000000071>
0x00007000015bcdd8:  0x000000c000000ea0  0x00007000015bce18
0x00007000015bcde8:  0x00000000040369f0 <runtime.fatalthrow+0x0000000000000050>  0x00007000015bcdf8
0x00007000015bcdf8:  0x0000000004036a20 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c000000ea0
0x00007000015bce08:  0x00000000040367b1 <runtime.throw+0x0000000000000071>  0x00007000015bce28
0x00007000015bce18:  0x00007000015bce48  0x00000000040367b1 <runtime.throw+0x0000000000000071>
0x00007000015bce28:  0x00007000015bce30  0x00000000040367e0 <runtime.throw.func1+0x0000000000000000>
0x00007000015bce38:  0x0000000004385563  0x000000000000002a
0x00007000015bce48:  0x00007000015bce98  0x000000000404c176 <runtime.sigpanic+0x0000000000000396>
0x00007000015bce58: <0x0000000004385563  0x000000000000003c
0x00007000015bce68:  0x0000000000000000  0x00007000015bceb0
0x00007000015bce78:  0x00007fff2028bc33  0x0000000000002000
0x00007000015bce88:  0x000000c000000008  0x0000000000000000
0x00007000015bce98:  0x00007000015bcee0 !0x00007fff20358cbe
0x00007000015bcea8: >0x00007000015bcee0  0x00000000045b8000
0x00007000015bceb8:  0x00000000000003d6  0x00000000040f5825 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007000015bcec8:  0x000000000406859f <runtime.syscall+0x000000000000001f>  0x000000c00030edc0
0x00007000015bced8:  0x000000000406826b <runtime.usleep_trampoline+0x000000000000000b>  0x000000c00030ed90
0x00007000015bcee8:  0x0000000004066410 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007000015bcef8:  0x000000c000001e00  0x1e00000400000002
0x00007000015bcf08:  0x000000c000000ea0  0x000000c000000b60
0x00007000015bcf18:  0x0000000000001298  0x000000c0002a4000
0x00007000015bcf28:  0x0000000004064529 <runtime.systemstack+0x0000000000000049>  0x00007000015bcf50
runtime.throw({0x4385563, 0x3c})
        /usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20358cbe
stack: frame={sp:0x7000015bce58, fp:0x7000015bcea8} stack=[0x70000153d338,0x7000015bcf38)
0x00007000015bcd58:  0x01007000015bcd78  0x0000000000000004
0x00007000015bcd68:  0x000000000000001f  0x00007fff20358cbe
0x00007000015bcd78:  0x0b01dfacedebac1e  0x0000000000000001
0x00007000015bcd88:  0x00000000040367b1 <runtime.throw+0x0000000000000071>  0x00007000015bce28
0x00007000015bcd98:  0x0000000004380186  0x00007000015bcde0
0x00007000015bcda8:  0x0000000004036a68 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000c000000ea0
0x00007000015bcdb8:  0x0000000000000001  0x0000000000000001
0x00007000015bcdc8:  0x00007000015bce28  0x00000000040367b1 <runtime.throw+0x0000000000000071>
0x00007000015bcdd8:  0x000000c000000ea0  0x00007000015bce18
0x00007000015bcde8:  0x00000000040369f0 <runtime.fatalthrow+0x0000000000000050>  0x00007000015bcdf8
0x00007000015bcdf8:  0x0000000004036a20 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c000000ea0
0x00007000015bce08:  0x00000000040367b1 <runtime.throw+0x0000000000000071>  0x00007000015bce28
0x00007000015bce18:  0x00007000015bce48  0x00000000040367b1 <runtime.throw+0x0000000000000071>
0x00007000015bce28:  0x00007000015bce30  0x00000000040367e0 <runtime.throw.func1+0x0000000000000000>
0x00007000015bce38:  0x0000000004385563  0x000000000000002a
0x00007000015bce48:  0x00007000015bce98  0x000000000404c176 <runtime.sigpanic+0x0000000000000396>
0x00007000015bce58: <0x0000000004385563  0x000000000000003c
0x00007000015bce68:  0x0000000000000000  0x00007000015bceb0
0x00007000015bce78:  0x00007fff2028bc33  0x0000000000002000
0x00007000015bce88:  0x000000c000000008  0x0000000000000000
0x00007000015bce98:  0x00007000015bcee0 !0x00007fff20358cbe
0x00007000015bcea8: >0x00007000015bcee0  0x00000000045b8000
0x00007000015bceb8:  0x00000000000003d6  0x00000000040f5825 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007000015bcec8:  0x000000000406859f <runtime.syscall+0x000000000000001f>  0x000000c00030edc0
0x00007000015bced8:  0x000000000406826b <runtime.usleep_trampoline+0x000000000000000b>  0x000000c00030ed90
0x00007000015bcee8:  0x0000000004066410 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007000015bcef8:  0x000000c000001e00  0x1e00000400000002
0x00007000015bcf08:  0x000000c000000ea0  0x000000c000000b60
0x00007000015bcf18:  0x0000000000001298  0x000000c0002a4000
0x00007000015bcf28:  0x0000000004064529 <runtime.systemstack+0x0000000000000049>  0x00007000015bcf50
runtime.sigpanic()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/signal_unix.go:719 +0x396

goroutine 35 [syscall]:
syscall.syscall(0x40f5820, 0x1, 0x40487413, 0xc00030ee50)
        /usr/local/Cellar/go/1.17/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00030edc0 sp=0xc00030eda0 pc=0x40630db
syscall.syscall(0x0, 0x0, 0x0, 0x0)
        <autogenerated>:1 +0x26 fp=0xc00030ee08 sp=0xc00030edc0 pc=0x4068d46
golang.org/x/sys/unix.ioctl(0x0, 0x0, 0x0)
        /Users/dc18devmacosxi/go/pkg/mod/golang.org/x/sys@v0.0.0-20191026070338-33540a1f6037/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc00030ee38 sp=0xc00030ee08 pc=0x40f54b9
golang.org/x/sys/unix.IoctlGetTermios(...)
        /Users/dc18devmacosxi/go/pkg/mod/golang.org/x/sys@v0.0.0-20191026070338-33540a1f6037/unix/ioctl.go:63
github.com/sirupsen/logrus.isTerminal(0xc00030f418)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/terminal_check_bsd.go:11 +0x50 fp=0xc00030eea8 sp=0xc00030ee38 pc=0x40fb370
github.com/sirupsen/logrus.checkIfTerminal({0x43e8280, 0xc000118008})
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/terminal_check_notappengine.go:13 +0x75 fp=0xc00030eec0 sp=0xc00030eea8 pc=0x40fb415
github.com/sirupsen/logrus.(*TextFormatter).init(0xc00011a420, 0x3)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:103 +0x34 fp=0xc00030ef40 sp=0xc00030eec0 pc=0x40fb4f4
github.com/sirupsen/logrus.(*TextFormatter).Format.func1()
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:193 +0x25 fp=0xc00030ef60 sp=0xc00030ef40 pc=0x40fcba5
sync.(*Once).doSlow(0x43ef478, 0xc000312100)
        /usr/local/Cellar/go/1.17/libexec/src/sync/once.go:68 +0xd2 fp=0xc00030efc8 sp=0xc00030ef60 pc=0x40791b2
sync.(*Once).Do(...)
        /usr/local/Cellar/go/1.17/libexec/src/sync/once.go:59
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00011a420, 0xc000312070)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:193 +0xebe fp=0xc00030f538 sp=0xc00030efc8 pc=0x40fc55e
github.com/sirupsen/logrus.(*Entry).write(0xc000312070)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:271 +0xa5 fp=0xc00030f5b0 sp=0xc00030f538 pc=0x40f9a45
github.com/sirupsen/logrus.Entry.log({0xc00012c000, 0xc000308000, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:247 +0x25a fp=0xc00030f628 sp=0xc00030f5b0 pc=0x40f96da
github.com/sirupsen/logrus.(*Entry).Log(0xc000312000, 0x4, {0xc00030f8f0, 0x43781d6, 0x0})
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xa8 fp=0xc00030f730 sp=0xc00030f628 pc=0x40f9c68
github.com/sirupsen/logrus.(*Entry).Info(...)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:300
main.proc_generic.func1()
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/proc_generic.go:116 +0x137 fp=0xc00030ffe0 sp=0xc00030f730 pc=0x42cb057
runtime.goexit()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00030ffe8 sp=0xc00030ffe0 pc=0x4066701created by main.proc_generic
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/proc_generic.go:115 +0x87a

goroutine 1 [runnable]:
main.coroHttpServer(0xc0002a0000)
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/http_server.go:14 +0x85
main.runMain(0xc00012a1e0)
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/main.go:314 +0x125
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc000185e40)
        /Users/dc18devmacosxi/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x312
main.main()
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/main.go:50 +0x652

goroutine 50 [runnable]:
context.propagateCancel({0x43f0868, 0xc0000be040}, {0x43edb60, 0xc0000d6040})
        /usr/local/Cellar/go/1.17/libexec/src/context/context.go:250 +0x235
context.WithCancel({0x43f0868, 0xc0000be040})
        /usr/local/Cellar/go/1.17/libexec/src/context/context.go:237 +0xd0
net.(*Resolver).lookupIPAddr(0x460f120, {0x43f04b0, 0xc00011c008}, {0x4374632, 0xe}, {0xc0000c2010, 0x9})
        /usr/local/Cellar/go/1.17/libexec/src/net/lookup.go:290 +0x394
net.(*Resolver).internetAddrList(0x43f04b0, {0x43f04b0, 0xc00011c008}, {0x4374632, 0x3}, {0xc0000c2010, 0xe})
        /usr/local/Cellar/go/1.17/libexec/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0xc00011c008, {0x43f04b0, 0xc00011c008}, {0x43749f0, 0x4}, {0x4374632, 0x4377540}, {0xc0000c2010, 0xe}, {0x0, ...})
        /usr/local/Cellar/go/1.17/libexec/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0x460fa00, {0x43f04b0, 0xc00011c008}, {0x4374632, 0xc000206a40}, {0xc0000c2010, 0x118})
        /usr/local/Cellar/go/1.17/libexec/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0xc000206c80, {0x43f04b0, 0xc00011c008}, {0x4374632, 0x21}, {0xc0000c2010, 0xc0000be020})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:1175 +0xb8
net/http.(*Transport).dialConn(0xc00026a140, {0x43f04b0, 0xc00011c008}, {{}, 0x0, {0xc0000bc000, 0x5}, {0xc0000c2010, 0xe}, 0x0})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x40c7f0d, 0xc0000d8000)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:1415 +0x3d7

goroutine 34 [select]:
net/http.(*Transport).getConn(0xc00026a140, 0xc0000d6000, {{}, 0x0, {0xc0000bc000, 0x5}, {0xc0000c2010, 0xe}, 0x0})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc00026a140, 0xc0000c8000)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0001815f0, 0x43e7fc0)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc0000c8000, {0x43e7fc0, 0xc00026a140}, {0x4366da0, 0x53a6901, 0x0})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00020aff0, 0xc0000c8000, {0xb, 0x377a8c, 0x0})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00020aff0, 0xc0000c8000)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:593
net/http.(*Client).Post(0xc000206c80, {0xc0000bc000, 0xcc0000c0000ba010}, {0x4381265, 0x21}, {0x43e8380, 0xc0000be020})
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:858 +0x148
net/http.(*Client).PostForm(0x4349900, {0xc0000bc000, 0x25}, 0x437847d)
        /usr/local/Cellar/go/1.17/libexec/src/net/http/client.go:896 +0xa9
main.(*ControlFloor).login(0xc000252300)
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/controlfloor.go:555 +0x249
main.NewControlFloor.func2()
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/controlfloor.go:101 +0x7a
created by main.NewControlFloor
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/controlfloor.go:89 +0x4b7

goroutine 21 [syscall]:
os/signal.signal_recv()
        /usr/local/Cellar/go/1.17/libexec/src/runtime/sigqueue.go:166 +0x28
os/signal.loop()
        /usr/local/Cellar/go/1.17/libexec/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        /usr/local/Cellar/go/1.17/libexec/src/os/signal/signal.go:151 +0x2c

goroutine 37 [runnable]:
main.coro_sigterm.func1()
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/shutdown.go:19
created by main.coro_sigterm
        /Users/dc18devmacosxi/Github/iOS_Remote_Control/ios_remote_provider/shutdown.go:19 +0xf7
root@MAC-Big-Sur-2 ios_remote_provider %

`============================

Do we have any workaround or solution to fix this issue?

Thanks in advance,

**Comment by nanoscopic** [comment]
There is something wrong with Golang 1.17 on some machines with MacOS. It works fine if you downgrade / build with Golang 1.16. I'd recommend that for now.

The crashes I've seen ( both myself and from reporting users ) appear to have the problem originating within logrus. The end problem is within Golang, so I'd consider it a Golang bug at the moment.

**Comment by ngtrphuong** [comment]
Thanks for the quick respond, @nanoscopic 
Let's me try it now and get back to you if any,

**Comment by ngtrphuong** [comment]
It works flawlessly,

BTW, what is the credential I need to input to log into ControlFloor Web app?

![image](https://user-images.githubusercontent.com/12130031/133551546-3318066b-303a-421c-9fe6-aa1c25d7601f.png)

Tried searching in the codes and README files but don't have any clue about this credential to login,

**Comment by sonusainier** [comment]
@ngtrphuong  
user = ok
pass = ok

**Comment by ngtrphuong** [comment]
I can login to CF and can access iPhone instance. However, the black screen displays and WDA crash with logs and snapshot below - 

![image](https://user-images.githubusercontent.com/12130031/133552503-f1377ab7-083e-4e35-9f9b-c24730a022bf.png)


![image](https://user-images.githubusercontent.com/12130031/133552709-5fb64bfa-f8ab-4661-8195-55cbe41acee9.png)

Not sure what is the exact issue,

**Comment by nanoscopic** [comment]
The issue is that WDA is not running/staying running properly on your device.

See the lines "WARN Process end - wda"? Those should not be occurring.

That means that when the provider attempts to start WDA for the device it is failing to do so.

Have you installed the WebDriverAgent to your device? Have you installed the video app to your device?

**Comment by ngtrphuong** [comment]
I have done with all of those,

The Video App is running and in Video Broadcasting mode while the WDA was built and tested successfully,

BTW, let me check 1 more round to determine why this message happened,

Thanks again, @nanoscopic

**Comment by ngtrphuong** [comment]
Finally, I got WDA, CF VidStream working but still done see iPhone Screen in browser,

Everything seems goes smoothly except the phone screen and interaction with it,

See snapshots below - 

![image](https://user-images.githubusercontent.com/12130031/133571886-5fafc817-2f4f-42ae-9698-44794cf671e9.png)

![image](https://user-images.githubusercontent.com/12130031/133571948-97e534f2-b53c-450d-a0d2-b8ca1724e608.png)

Is there any missing caused the video cannot be broadcast in this case?

**Comment by ngtrphuong** [comment]
Close as this issue was gone away after downgrade Golang to < 1.17,
