### ISSUE TITLE
Can't see any device connected 

### ISSUE THREAD

**Issue by AmandeepT** [nanoscopic/ios_remote_provider#61]
Hi I have done the required configuration successfully and can't see any device connected in Control Floor. I have used 4 different devices (iPhone-8 IOS-14.2, iPhone-Xs-IOS 14.5.1, 11ProMax-IOS 14.2 and 12-IOS-14.7.1 ), please suggest.

<img width="1282" alt="Screen Shot 2021-09-25 at 2 13 21 am" src="https://user-images.githubusercontent.com/79556814/134707975-c3f9fe7b-f81b-4712-b299-d9d75355179a.png">

**Comment by s4ib0t87** [comment]
Hi AmandeepT,

looks like your ios_remote_provider is not notifying ControlFloor that your device exists.
Did you add your device in the config.json file? You need to add it like the following example

config.json
```
    devices:[
        {
            udid:"your-device-udid"
            uiWidth:375
            uiHeight:812
            controlCenterMethod:"topdown"
        }
    ]
```

**Comment by AmandeepT** [comment]
Hi s4ib0t87,

Yes, I did update the udid of the devices I used and then ran below commands

in Provider:

make
make wda
./main register
./main run

Controler:
./main run

**Comment by s4ib0t87** [comment]
Is the log on the left side the whole log for your ios_remote_provider? Seems very little, have you connected an mobile while you start the ios_remote_provider? 

can you please post you config.json from ios_remote_provider and ControlFloor?

**Comment by AmandeepT** [comment]
Hi, please find below the config.json output.

iOS_remote_provider:-
{
    controlfloor: {
        host: ":8080"
        username: "first"
        https: true
        selfSigned: true
    }
    wda: {
        // Your Apple Developer Team OU
        // If you don't know this, you can find it by running ./util/signers.pl
        devTeamOu: "6G9GD5K24V"
        
        // Some unique Bundle ID prefix to usefor the Bundle IDs for WebDriverAgent
        // This default, "com.appium", will likely work for paid developer accounts
        // Make sure the provisioning profile you setup has a wildcard identifier matching this
        // The two identifiers that will be made if "com.appium" is used are
        // "com.appium.WebDriverAgentLib"
        // "com.appium.WebDriverAgentRunner"
        // If you are using a free developer account, you will not have any provisioning profile,
        //   so you will need to set this bundle prefix to something globally unique, such as
        //   "com.[your name]"
        bundleIdPrefix: "com.dryark"
        
        runner: {
            buildStyle: "Automatic" // or "Manual"
            provisioningProfile: "" // specify when buildStyle is Manual
        }
        
        startMethod: "tidevice"
    },
    vidapp: {
        devTeamOu: "6G9GD5K24V"
        bundleIdPrefix: "com.dryark"
    },
    devices: [
        {
            udid: "00008020-000621441ED8003A"
            uiWidth: 414
            uiHeight: 896
            controlCenterMethod: "topDown"
        }
    ]
}


control floor:

{
    // This listens on all interfaces on port 8080
    listen: ":8080"
    
    https: true
    
    auth: {
        // "builtin" uses builtin database based auth
        // "mod" additionally checks for controlfloor_auth mod based auth
        type: "mod"
    }
    
    video: {
        // The maximum vertical size in pixels of displayed video when viewing
        //   device video in CF
        maxHeight: 1000
    }
    
    notes: [
        {
            short: "NOTE: Password fields"
            long: "Password fields and the text entered into them are invisible on the display. You can still select them by clicking where they are, and enter text into them using the keyboard, but you will not be able to see the text as you are entering it."
        }
        {
            short: "<i style='font-size: 30px; vertical-align: middle;' class='mdi mdi-anvil mInactive'></i> Firm press"
            long: "The anchor icon causes clicks on the screen to become 'Firm Presses' on the device. It is active when the icon is red."
            tie: "hardpress"
        }
        {
            short: "<i style='font-size: 30px; vertical-align: middle;' class='mdi mdi-alarm mInactive'></i> Long press"
            long: "The clock icon causes clicks on the screen to become 'Long Presses' on the device. A 'long press' is equivalent to holding your finger down on the device for a few seconds. It is active when the icon is red."
            tie: "longpress"
        }
    ]
}

**Comment by s4ib0t87** [comment]
maybe give it a try with changing the controlfloor.host in the ios_remote_provider/config.json 
from host: ":8080" to host:"localhost:8080"

**Comment by nanoscopic** [comment]
There was a particular version committed some 2 weeks ago now that incorrectly activated "single id mode" when it should not be activated. It was fixed within 2 days ( next day I believe )

It is clear from logs shown above that you are using that particular broken version.

Pull the various updates, rebuild, and rerun and it will not do that.

**Comment by AmandeepT** [comment]
HI Nanoscopic, thanks I will try that today.

**Comment by AmandeepT** [comment]
Hi, I can see the phones now, but I can see the screen /video. <img width="1089" alt="Screen Shot 2021-10-01 at 7 46 09 pm" src="https://user-images.githubusercontent.com/79556814/135600262-9db331e6-df4d-49d9-8cac-64f3bbac0cb7.png">



provider log:

./main run
Registering user routes
Registering provider routes
Registering device routes
Provider with username first already existed
  Updating password to 94918d3033dbd400812bd97f6de57a59
  After update: 94918d3033dbd400812bd97f6de57a59
Provider login user=first pass=94918d3033dbd400812bd97f6de57a59
provider login ok
provider user=first
devStatus request; variant=exists
  udid=00008101-001904CC11A3003A
Notified that device 00008101-001904CC11A3003A exists
Adding device:
  udid:00008101-001904CC11A3003A
  name:unknown
  clickWidth:414
  clickHegiht:896
Device with udid 00008101-001904CC11A3003A already existed
provider user=first
got ws connection
provider user=first
devStatus request; variant=info
  udid=00008101-001904CC11A3003A
Device info for 00008101-001904CC11A3003A:
{"ProductType":"iPhone13,2","InternationalMobileEquipmentIdentity":"357676154196899","UniqueDeviceID":"00008101-001904CC11A3003A","InternationalMobileSubscriberIdentity":"505013507483786","DeviceName":"Phone","EthernetAddress":"d8:de:3a:41:1a:ce","ModelNumber":"MGJE3","HardwareModel":"D53gAP","PhoneNumber":"+61 400 000 582","ProductVersion":"14.7.1","ArtworkDeviceProductDescription":"iPhone 12"
}
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
uauth
checking for ok
user fail
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
login ok; user=ok
Reserving device 00008101-001904CC11A3003A for ok
      INFO[0040] Image stream connected                        rid=zgbaiCMRAj type=imgstream_start udid="***003A"
Response from browser: {"clientTime":"1633081746020","sentTime":"1633081746019"}
Client time:1633081746020
Milliseconds to client:0
Client Offset:-1
sending startStream to provider
sending {id:0,type:"startStream",udid:"00008101-001904CC11A3003A"}

provider user=first
connection to provider/imgStream udid=00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
provider user=first
devStatus request; variant=wdaStopped
  udid=00008101-001904CC11A3003A
WDA stopped for 00008101-001904CC11A3003A
sending {id:2234,type:"home",udid:"00008101-001904CC11A3003A"}

received 






iOS_remote_provider logs:

./main register
WARN Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
Enter registration password:
Using default registration password of doreg
Registered and got password 94918d3033dbd400812bd97f6de57a59
User first existed so password was renewed
d807294@CMM-C02DR2SHMD6N ios_remote_provider % ./main run     
WARN Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
WARN Leftover go-ios - Sending SIGTERM             args="[forward --udid 00008101-001904CC11A3003A 8101 8101]" pid=71355 proc=go-ios type=proc_cleanup
WARN Leftover go-ios - Sending SIGTERM             args="[server --port 8105]" pid=71358 proc=go-ios type=proc_cleanup
INFO Logged in to control floor                    type=cf_login_success
WARN ControlFloor connection is self signed        type=cf_ws_selfsign
INFO Connecting ControlFloor WebSocket             link="wss://localhost:8080/provider/ws" type=cf_ws_connect
INFO Notifying CF of device existence              name="device existence" type=cf_notify udid="***003A" values="map[clickHeight:[896] clickWidth:[414] height:[896] udid:[00008101-001904CC11A3003A] width:[414]]"
INFO Device Present                                type=dev_present uuid="***003A"
INFO Device Info                                   ModelNumber=MGJE3 ProductType="iPhone13,2" ProductVersion=14.7.1 type=dev_info_basic uuid="***003A"
INFO Notifying CF of device info                   name="device info" type=cf_notify udid="***003A" values="map[info:[{\"ProductType\":\"iPhone13,2\",\"InternationalMobileEquipmentIdentity\":\"357676154196899\",\"UniqueDeviceID\":\"00008101-001904CC11A3003A\",\"InternationalMobileSubscriberIdentity\":\"505013507483786\",\"DeviceName\":\"Phone\",\"EthernetAddress\":\"d8:de:3a:41:1a:ce\",\"ModelNumber\":\"MGJE3\",\"HardwareModel\":\"D53gAP\",\"PhoneNumber\":\"+61 400 000 582\",\"ProductVersion\":\"14.7.1\",\"ArtworkDeviceProductDescription\":\"iPhone 12\"\n}] udid:[00008101-001904CC11A3003A]]"
Starting bin/go-ios with [forward --udid 00008101-001904CC11A3003A 8101 8101]
INFO Process start - tunnel_8101->8101             binary=bin/go-ios proc="tunnel_8101->8101" type=proc_start
tunnel start:{"level":"info","msg":"Start listening on port 8101 forwarding to port 8101 on device","time":"2021-10-01T19:48:43+10:00"}
Starting WDA via bin/go-ios with args runwda --bundleid com.appium.WebDriverAgentRunner.xctrunner --testrunnerbundleid com.appium.WebDriverAgentRunner.xctrunner --xctestconfig WebDriverAgentRunner.xctest --udid 00008101-001904CC11A3003A
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
INFO Process start - syslogMonitor                 binary=bin/go-ios proc=syslogMonitor type=proc_start udid=00008101-001904CC11A3003A
INFO Process start - backupVideo                   binary=bin/go-ios port=8105 proc=backupVideo type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
Got request to start video stream for 00008101-001904CC11A3003A
self signed option
Connecting to CF imgStream
Connected CF imgStream
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
INFO Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN Process end - wda                             proc=wda type=proc_end
INFO Notifying CF of WDA stop                      name="WDA stop" type=cf_notify udid="***003A" values="map[udid:[00008101-001904CC11A3003A]]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x42ffb1c]

goroutine 57 [running]:
main.(*WDA).home(0xc0000d8630)
	/Users/d807294/Desktop/WDV/ios_remote_provider/wda.go:340 +0x3c
main.(*Device).home(...)
	/Users/d807294/Desktop/WDV/ios_remote_provider/device.go:570
main.(*ControlFloor).openWebsocket.func5()
	/Users/d807294/Desktop/WDV/ios_remote_provider/controlfloor.go:298 +0x5f
created by main.(*ControlFloor).openWebsocket
	/Users/d807294/Desktop/WDV/ios_remote_provider/controlfloor.go:295 +0xb3e
d807294@CMM-C02DR2SHMD6N ios_remote_provider %
