### ISSUE TITLE
Fantastic project，how can I modify the frame rate to make it smooth

### ISSUE THREAD

**Issue by kongfanjue** [nanoscopic/ios_remote_provider#68]

**Comment by nanoscopic** [comment]
When using the video app for video ( which now requires `videoMode: "app"` device specific configuration ), the "framerate" is determined by taking the framerate provided by iOS to the video app and dividing by 4. If you want more frames you can adjust this division and deploy the modified app with your adjustment.

The line of code to adjust is this one: https://github.com/nanoscopic/ios_video_app/blob/main/vidstream/vidstream_ext/SampleHandler.m#L625

Besides this, framerate will also be limited by the bandwidth of your connection to the CF server machine. If your bandwidth is low the framerate will be automatically dropped to match your bandwidth.
