### ISSUE TITLE
Opening video: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aridavis** [nanoscopic/ios_remote_provider#79]
Hello, I'm not sure why this is happening, when I opened video page in controlfloor, it returned an error

```
Connecting to CF imgStream
Connected CF imgStream
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4303553]

goroutine 162 [running]:
main.(*CFA).Screenshot(0xc0003b81e0)
        /Users/aridavis/Documents/x/ios_remote_provider/cfa.go:659 +0x73
main.(*Device).startVidStream(0xc0001ae000)
        /Users/aridavis/Documents/x/ios_remote_provider/device.go:589 +0x4c
main.(*ControlFloor).startVidStream(...)
        /Users/aridavis/Documents/x/ios_remote_provider/controlfloor.go:164
main.(*ControlFloor).openWebsocket.func15()
        /Users/aridavis/Documents/x/ios_remote_provider/controlfloor.go:424 +0x3c
created by main.(*ControlFloor).openWebsocket
        /Users/aridavis/Documents/x/ios_remote_provider/controlfloor.go:424 +0x1995
```

Do you guys have any solution? thank you

**Comment by mr-ichelyshkin** [comment]
Most likely you do not have CFA-agent runner installed in your device.
Try this:
`
./bin/iosif install -path ./bin/cfa/Debug-iphoneos/CFAgent-Runner.app
`
_[iosif](https://github.com/nanoscopic/iosif) will install CFAgent-Runner.app in your device_ 

In finally in your device should be two apps:
- CF Vidstream
- CF Agent-Runner

--
I hope this helps you.

**Comment by aridavis** [comment]
> Most likely you do not have CFA-agent runner installed in your device. Try this: `./bin/iosif install -path ./bin/cfa/Debug-iphoneos/CFAgent-Runner.app` _[iosif](https://github.com/nanoscopic/iosif) will install CFAgent-Runner.app in your device_
> 
> In finally in your device should be two apps:
> 
> * CF Vidstream
> * CF Agent-Runner
> 
> -- I hope this helps you.

Hi, it is working now, but I didn't use iosif since my terminal told me that it wasn't exists in the directory. I used FB-IDB to install the app, and it works now.. 

Thank you
