### ISSUE TITLE
Startup Issues - Issue unclear

### ISSUE THREAD

**Issue by ormoran** [nanoscopic/ios_remote_provider#8]
Hi!

I did (or at least I think I did) everything pretty much as in the tutorial, unfortunately I cannot see any devices int the list :(
![Screenshot 2021-03-18 at 09 39 08](https://user-images.githubusercontent.com/7736628/111598448-86886d80-87cf-11eb-9853-e7841afd2c7b.png)

**Additional info:**
- both provider and server are working on one machine
- vidtest2/screen recording is running on my iPad (with 14.4)
- WDA is also installed on the device
- device is visible in Xcode
![image](https://user-images.githubusercontent.com/7736628/111599087-33fb8100-87d0-11eb-8a48-9c46a5afe346.png)
- apart from my iPad I tried iPhone se (with the same result)
- I am a rookie in Xcode/apple stuff 
- I am using http for both provider and server

I have the feeling that the problem is between the keyboard and the chair so apologies if I am doing something wrong :(

Thx in advance for the answer.

**Comment by kristeedev** [comment]
Hi @ormoran 

please register ios_remote_provider first (set the default password by pressing enter:
cd ios_remote_provider
Build ios_remote_provider as mentioned in README.
./main register
<Continue with default password - Press enter when it prompts>
./main run 
Now see controlfloor, devices should appear.

**Comment by ormoran** [comment]
Hi,

Thx for the answer. As advised I went through the README again as follows:
`ormo@Sherlocks-Mac-mini ios_remote_provider % brew install nng  
Warning: nng 1.4.0 is already installed and up-to-date.
To reinstall 1.4.0, run:
  brew reinstall nng
ormo@Sherlocks-Mac-mini ios_remote_provider % make
make -C repos/iosif
make[1]: Nothing to be done for `all'.
ormo@Sherlocks-Mac-mini ios_remote_provider % security unlock-keychain login.keychain
password to unlock login.keychain: 
ormo@Sherlocks-Mac-mini ios_remote_provider % make wda
make: Nothing to be done for `wda'.
ormo@Sherlocks-Mac-mini ios_remote_provider % ./main register
Enter registration password:
Using default registration password of doreg
{"Success":true,"Password":"c3b78519052598cc1ced9c2615893c3b","Existed":true}
Registered and got password c3b78519052598cc1ced9c2615893c3b
User first existed so password was renewed
ormo@Sherlocks-Mac-mini ios_remote_provider % ./main run
Location from redirect of controlfloor login:'http://localhost:8080/provider/'
Logged in to control floor
link for dialer = ws://localhost:8080/provider/ws
INFO[0000] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
ormo@Sherlocks-Mac-mini ios_remote_provider %           
`
Unfortunately still no devices :(
Next I tried to remove both controlfloor and provider and pulled/reinstalled everything again (only difference is that i run contorl floor web on different port -> 8081). 
Unfortunately with the same effect: 
![image](https://user-images.githubusercontent.com/7736628/111766173-86f33800-88a5-11eb-9d43-94916d2d26b7.png)
![image](https://user-images.githubusercontent.com/7736628/111766799-3b8d5980-88a6-11eb-9139-55996b51bedb.png)

**My questions:**

- Is iOS 14.4 supported?
- Does it matter if I use http instead of https?
- What does: "sending {id:21132,type:"ping"} user fail" mean in the controlfloor context?
- Is there a way to see if the device is visible for the provider?
- Shoudl I see any output for "security unlock-keychain login.keychain" (as I am not getting any output after executing it)? 

Apologies for my lack of knowledge and thx in advance once again for the answer.

Regads,
Michal

**Comment by kristeedev** [comment]
Both ios_remote_provider and controlfloor should be running in the background. Seems like ios_remote_provider was not running. `cd ios_remote_provider` and run `./main run #This should keep running and should never exit`

**Comment by ormoran** [comment]
Its always this way and I cannot really determine whats wrong :/

_ormo@Sherlocks-Mac-mini ios_remote_provider % ./main run
Location from redirect of controlfloor login:'http://localhost:8081/provider/'
Logged in to control floor
link for dialer = ws://localhost:8081/provider/ws
INFO[0000] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
ormo@Sherlocks-Mac-mini ios_remote_provider %_

any idea why or where to look for an answer?

**Comment by nanoscopic** [comment]
The provider needs to be running for a device to be connected to ControlFloor and controllable there. The provider is what receives and relays commands to devices, and relays video from the devices to CF.

If no devices are connected, the provider is just waiting for a device connect event, so it is reasonable ( and generally should ) just always be running.

iOS 12+ is supported, including iOS 14.whatever
You should be able to use either http or https so long as both CF and provider are configured the same way. I've only been testing with https enabled lately though.

If you see `user fail` in the output, that indicates that you need to rerun `provider/main -register`

Various status messages are sent from provider to CF during startup of the device provision. That status is stored in the CF database, but is not yet displayed anywhere in the UI. TODO

For what it's worth, I've never had to unlock my keychain to get anything working. My machine may just be configured in a non-standard way though.

To my knowledge simulators don't support upload broadcast extensions, and therefore you cannot run vidtest on a simulator. To support video form simulators I will have to integrate portions of idb.

**Comment by ormoran** [comment]
Hi @nanoscopic ,

Many thx for the answer! I cannot get the provider running no matter how many times I try to register it. Can you please tell me how to access this local CF db so I can check status/errors? If a device is not theoretically needed for the provider to be running, it seems that something on my mac is blocking the resources/port/etc that the provider wants to use (so it exits instantly).

Regards,
Michal

**Comment by nanoscopic** [comment]
The local CF DB is a plain sqlite DB in the single file controlfloor/db.sqlite3
You can open it on a CLI with `sqlite3 db.sqlite3`
From the sqlite prompt you can type `.dump provider` to dump the provider entries.

If you delete that db file, it will be recreated automatically when CF is started.

It is certainly possible that MacOS restrictions are terminating the process immediately. The only way I've been testing running it myself is by running it in an iterm window that has already been granted full permissions. You should check your permissions in Settings. If at any point you answered 'no' to a permission prompt, or in some cases simply didn't notice the prompt before it vanished, then the system can default to blocking port usage.

**Comment by nanoscopic** [comment]
Unclear of the status of this issue. Is it working now with latest updates?

Is this still an issue in the same way described above?

**Comment by ormoran** [comment]
Hi, after reset Mac Mini to factory settings and doing everything from scratch it started to work :D 
Ill close the issue.
