### ISSUE TITLE
Issue in making wda

### ISSUE THREAD

**Issue by himanshunamdeo** [nanoscopic/ios_remote_provider#9]
Hi @nanoscopic,

While building the ios remote provider i am getting below error: 

touch python/deps_installed
mkdir repos/WebDriverAgent/build
./python/configure_wda.py muxed.json
make: ./python/configure_wda.py: No such file or directory
make: *** [repos/WebDriverAgent/build] Error 1

**Comment by kristeedev** [comment]
Was this after running `make wda`

**Comment by himanshunamdeo** [comment]
Yes,
I tried giving the complete file path in the MAKEFILE but that didn't worked either.

**Comment by ormoran** [comment]
Hi, 

I am not an expert on this but, what do you see if you input "python -V"? I recall having problems like this as I had python 2.7 by default on my mac. I edited the makefile and added "python3" in the beginning of two lines with *.py file operations and moved forward.

Authors: please correct me if am wrong and apologies if so

Regards

**Comment by himanshunamdeo** [comment]
Hey @ormoran, 
Thanks, this worked for me. I was able to build ios provider successfully.
